// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            

            

            class CheckFriendResult  {
                final String userId;
final int result;

                const CheckFriendResult({required this.userId ,required this.result ,});

                
                

                
        @override
        int get hashCode => userId.hashCode^result.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is CheckFriendResult &&
                runtimeType == other.runtimeType
                && userId == other.userId&& result == other.result;
        
            }

class SearchFriendItem  {
                final String friendUserId;
final String nickname;
final String faceUrl;
final String remark;
final String ex;
final PlatformInt64 createTime;
/// 1=好友, 2=黑名单
final int relationship;

                const SearchFriendItem({required this.friendUserId ,required this.nickname ,required this.faceUrl ,required this.remark ,required this.ex ,required this.createTime ,required this.relationship ,});

                
                

                
        @override
        int get hashCode => friendUserId.hashCode^nickname.hashCode^faceUrl.hashCode^remark.hashCode^ex.hashCode^createTime.hashCode^relationship.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is SearchFriendItem &&
                runtimeType == other.runtimeType
                && friendUserId == other.friendUserId&& nickname == other.nickname&& faceUrl == other.faceUrl&& remark == other.remark&& ex == other.ex&& createTime == other.createTime&& relationship == other.relationship;
        
            }
            