// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class CheckFriendResult {
  final String userId;
  final int result;

  const CheckFriendResult({required this.userId, required this.result});

  @override
  int get hashCode => userId.hashCode ^ result.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CheckFriendResult &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          result == other.result;
}
