// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/bridge_client.dart';
import 'api/listeners.dart';
import 'api/logger.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'im/auth.dart';
import 'im/types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1769084870;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_flutter_rust_demo',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiBridgeClientOpenImBridgeClientConnect({
    required OpenImBridgeClient that,
  });

  Stream<ConversationChangedEvent>
  crateApiBridgeClientOpenImBridgeClientConversationEvent({
    required OpenImBridgeClient that,
  });

  Future<List<LocalConversation>>
  crateApiBridgeClientOpenImBridgeClientGetAllConversations({
    required OpenImBridgeClient that,
  });

  Stream<MessageEvent> crateApiBridgeClientOpenImBridgeClientMessageEvent({
    required OpenImBridgeClient that,
  });

  OpenImBridgeClient crateApiBridgeClientOpenImBridgeClientNew({
    required String userId,
    required String token,
    required int platformId,
    String? wsUrl,
  });

  Stream<MessageEvent> crateApiListenersDartAdvancedMsgListenerNew();

  Stream<ConversationChangedEvent>
  crateApiListenersDartConversationListenerNew();

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  void crateApiLoggerInitLogger({required LoggerConfig config});

  void crateApiLoggerInitLoggerSimple({String? logLevel});

  Future<LoggerConfig> crateApiLoggerLoggerConfigDefault();

  Future<LoginResponse> crateApiBridgeClientLoginAsync({
    required String areaCode,
    required String phoneNumber,
    required String password,
    required int platform,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_OpenImBridgeClient;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_OpenImBridgeClient;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_OpenImBridgeClientPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiBridgeClientOpenImBridgeClientConnect({
    required OpenImBridgeClient that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBridgeClientOpenImBridgeClientConnectConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeClientOpenImBridgeClientConnectConstMeta =>
      const TaskConstMeta(
        debugName: "OpenImBridgeClient_connect",
        argNames: ["that"],
      );

  @override
  Stream<ConversationChangedEvent>
  crateApiBridgeClientOpenImBridgeClientConversationEvent({
    required OpenImBridgeClient that,
  }) {
    final sink = RustStreamSink<ConversationChangedEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
              that,
              serializer,
            );
            sse_encode_StreamSink_conversation_changed_event_Sse(
              sink,
              serializer,
            );
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 2,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta:
              kCrateApiBridgeClientOpenImBridgeClientConversationEventConstMeta,
          argValues: [that, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta
  get kCrateApiBridgeClientOpenImBridgeClientConversationEventConstMeta =>
      const TaskConstMeta(
        debugName: "OpenImBridgeClient_conversation_event",
        argNames: ["that", "sink"],
      );

  @override
  Future<List<LocalConversation>>
  crateApiBridgeClientOpenImBridgeClientGetAllConversations({
    required OpenImBridgeClient that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_local_conversation,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateApiBridgeClientOpenImBridgeClientGetAllConversationsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiBridgeClientOpenImBridgeClientGetAllConversationsConstMeta =>
      const TaskConstMeta(
        debugName: "OpenImBridgeClient_get_all_conversations",
        argNames: ["that"],
      );

  @override
  Stream<MessageEvent> crateApiBridgeClientOpenImBridgeClientMessageEvent({
    required OpenImBridgeClient that,
  }) {
    final messageSink = RustStreamSink<MessageEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
              that,
              serializer,
            );
            sse_encode_StreamSink_message_event_Sse(messageSink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 4,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta:
              kCrateApiBridgeClientOpenImBridgeClientMessageEventConstMeta,
          argValues: [that, messageSink],
          apiImpl: this,
        ),
      ),
    );
    return messageSink.stream;
  }

  TaskConstMeta
  get kCrateApiBridgeClientOpenImBridgeClientMessageEventConstMeta =>
      const TaskConstMeta(
        debugName: "OpenImBridgeClient_message_event",
        argNames: ["that", "messageSink"],
      );

  @override
  OpenImBridgeClient crateApiBridgeClientOpenImBridgeClientNew({
    required String userId,
    required String token,
    required int platformId,
    String? wsUrl,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(userId, serializer);
          sse_encode_String(token, serializer);
          sse_encode_i_32(platformId, serializer);
          sse_encode_opt_String(wsUrl, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBridgeClientOpenImBridgeClientNewConstMeta,
        argValues: [userId, token, platformId, wsUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeClientOpenImBridgeClientNewConstMeta =>
      const TaskConstMeta(
        debugName: "OpenImBridgeClient_new",
        argNames: ["userId", "token", "platformId", "wsUrl"],
      );

  @override
  Stream<MessageEvent> crateApiListenersDartAdvancedMsgListenerNew() {
    final messageSink = RustStreamSink<MessageEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_message_event_Sse(messageSink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 6,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_dart_advanced_msg_listener,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiListenersDartAdvancedMsgListenerNewConstMeta,
          argValues: [messageSink],
          apiImpl: this,
        ),
      ),
    );
    return messageSink.stream;
  }

  TaskConstMeta get kCrateApiListenersDartAdvancedMsgListenerNewConstMeta =>
      const TaskConstMeta(
        debugName: "dart_advanced_msg_listener_new",
        argNames: ["messageSink"],
      );

  @override
  Stream<ConversationChangedEvent>
  crateApiListenersDartConversationListenerNew() {
    final sink = RustStreamSink<ConversationChangedEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_conversation_changed_event_Sse(
              sink,
              serializer,
            );
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 7,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_dart_conversation_listener,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiListenersDartConversationListenerNewConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiListenersDartConversationListenerNewConstMeta =>
      const TaskConstMeta(
        debugName: "dart_conversation_listener_new",
        argNames: ["sink"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  void crateApiLoggerInitLogger({required LoggerConfig config}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_logger_config(config, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiLoggerInitLoggerConstMeta,
        argValues: [config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLoggerInitLoggerConstMeta =>
      const TaskConstMeta(debugName: "init_logger", argNames: ["config"]);

  @override
  void crateApiLoggerInitLoggerSimple({String? logLevel}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(logLevel, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiLoggerInitLoggerSimpleConstMeta,
        argValues: [logLevel],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLoggerInitLoggerSimpleConstMeta =>
      const TaskConstMeta(
        debugName: "init_logger_simple",
        argNames: ["logLevel"],
      );

  @override
  Future<LoggerConfig> crateApiLoggerLoggerConfigDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_logger_config,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLoggerLoggerConfigDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLoggerLoggerConfigDefaultConstMeta =>
      const TaskConstMeta(debugName: "logger_config_default", argNames: []);

  @override
  Future<LoginResponse> crateApiBridgeClientLoginAsync({
    required String areaCode,
    required String phoneNumber,
    required String password,
    required int platform,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(areaCode, serializer);
          sse_encode_String(phoneNumber, serializer);
          sse_encode_String(password, serializer);
          sse_encode_i_32(platform, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_login_response,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBridgeClientLoginAsyncConstMeta,
        argValues: [areaCode, phoneNumber, password, platform],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeClientLoginAsyncConstMeta =>
      const TaskConstMeta(
        debugName: "login_async",
        argNames: ["areaCode", "phoneNumber", "password", "platform"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_OpenImBridgeClient => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_OpenImBridgeClient => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  OpenImBridgeClient
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return OpenImBridgeClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  OpenImBridgeClient
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return OpenImBridgeClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  OpenImBridgeClient
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return OpenImBridgeClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  OpenImBridgeClient
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return OpenImBridgeClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<ConversationChangedEvent>
  dco_decode_StreamSink_conversation_changed_event_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<MessageEvent> dco_decode_StreamSink_message_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  LoggerConfig dco_decode_box_autoadd_logger_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_logger_config(raw);
  }

  @protected
  LoginData dco_decode_box_autoadd_login_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_login_data(raw);
  }

  @protected
  ConversationChangedEvent dco_decode_conversation_changed_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return ConversationChangedEvent(
      conversationList: dco_decode_String(arr[0]),
    );
  }

  @protected
  DartAdvancedMsgListener dco_decode_dart_advanced_msg_listener(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return DartAdvancedMsgListener(
      messageSink: dco_decode_StreamSink_message_event_Sse(arr[0]),
    );
  }

  @protected
  DartConversationListener dco_decode_dart_conversation_listener(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return DartConversationListener(
      sink: dco_decode_StreamSink_conversation_changed_event_Sse(arr[0]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<LocalConversation> dco_decode_list_local_conversation(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_local_conversation).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  LocalConversation dco_decode_local_conversation(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 24)
      throw Exception('unexpected arr length: expect 24 but see ${arr.length}');
    return LocalConversation(
      conversationId: dco_decode_String(arr[0]),
      conversationType: dco_decode_i_32(arr[1]),
      userId: dco_decode_String(arr[2]),
      groupId: dco_decode_String(arr[3]),
      showName: dco_decode_String(arr[4]),
      faceUrl: dco_decode_String(arr[5]),
      latestMsg: dco_decode_String(arr[6]),
      latestMsgSendTime: dco_decode_i_64(arr[7]),
      unreadCount: dco_decode_i_32(arr[8]),
      recvMsgOpt: dco_decode_i_32(arr[9]),
      isPinned: dco_decode_bool(arr[10]),
      isPrivateChat: dco_decode_bool(arr[11]),
      burnDuration: dco_decode_i_32(arr[12]),
      groupAtType: dco_decode_i_32(arr[13]),
      isNotInGroup: dco_decode_bool(arr[14]),
      updateUnreadCountTime: dco_decode_i_64(arr[15]),
      attachedInfo: dco_decode_String(arr[16]),
      ex: dco_decode_String(arr[17]),
      draftText: dco_decode_String(arr[18]),
      draftTextTime: dco_decode_i_64(arr[19]),
      maxSeq: dco_decode_i_64(arr[20]),
      minSeq: dco_decode_i_64(arr[21]),
      isMsgDestruct: dco_decode_bool(arr[22]),
      msgDestructTime: dco_decode_i_64(arr[23]),
    );
  }

  @protected
  LoggerConfig dco_decode_logger_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return LoggerConfig(
      logLevel: dco_decode_String(arr[0]),
      logFilePath: dco_decode_String(arr[1]),
      isLogStandardOutput: dco_decode_bool(arr[2]),
    );
  }

  @protected
  LoginData dco_decode_login_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return LoginData(
      imToken: dco_decode_String(arr[0]),
      chatToken: dco_decode_String(arr[1]),
      userId: dco_decode_String(arr[2]),
    );
  }

  @protected
  LoginResponse dco_decode_login_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return LoginResponse(
      errCode: dco_decode_i_32(arr[0]),
      errMsg: dco_decode_String(arr[1]),
      data: dco_decode_opt_box_autoadd_login_data(arr[2]),
    );
  }

  @protected
  MessageEvent dco_decode_message_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return MessageEvent(message: dco_decode_String(arr[0]));
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  LoginData? dco_decode_opt_box_autoadd_login_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_login_data(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  OpenImBridgeClient
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return OpenImBridgeClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  OpenImBridgeClient
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return OpenImBridgeClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  OpenImBridgeClient
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return OpenImBridgeClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  OpenImBridgeClient
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return OpenImBridgeClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<ConversationChangedEvent>
  sse_decode_StreamSink_conversation_changed_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<MessageEvent> sse_decode_StreamSink_message_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  LoggerConfig sse_decode_box_autoadd_logger_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_logger_config(deserializer));
  }

  @protected
  LoginData sse_decode_box_autoadd_login_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_login_data(deserializer));
  }

  @protected
  ConversationChangedEvent sse_decode_conversation_changed_event(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_conversationList = sse_decode_String(deserializer);
    return ConversationChangedEvent(conversationList: var_conversationList);
  }

  @protected
  DartAdvancedMsgListener sse_decode_dart_advanced_msg_listener(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_messageSink = sse_decode_StreamSink_message_event_Sse(deserializer);
    return DartAdvancedMsgListener(messageSink: var_messageSink);
  }

  @protected
  DartConversationListener sse_decode_dart_conversation_listener(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sink = sse_decode_StreamSink_conversation_changed_event_Sse(
      deserializer,
    );
    return DartConversationListener(sink: var_sink);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<LocalConversation> sse_decode_list_local_conversation(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <LocalConversation>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_local_conversation(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  LocalConversation sse_decode_local_conversation(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_conversationId = sse_decode_String(deserializer);
    var var_conversationType = sse_decode_i_32(deserializer);
    var var_userId = sse_decode_String(deserializer);
    var var_groupId = sse_decode_String(deserializer);
    var var_showName = sse_decode_String(deserializer);
    var var_faceUrl = sse_decode_String(deserializer);
    var var_latestMsg = sse_decode_String(deserializer);
    var var_latestMsgSendTime = sse_decode_i_64(deserializer);
    var var_unreadCount = sse_decode_i_32(deserializer);
    var var_recvMsgOpt = sse_decode_i_32(deserializer);
    var var_isPinned = sse_decode_bool(deserializer);
    var var_isPrivateChat = sse_decode_bool(deserializer);
    var var_burnDuration = sse_decode_i_32(deserializer);
    var var_groupAtType = sse_decode_i_32(deserializer);
    var var_isNotInGroup = sse_decode_bool(deserializer);
    var var_updateUnreadCountTime = sse_decode_i_64(deserializer);
    var var_attachedInfo = sse_decode_String(deserializer);
    var var_ex = sse_decode_String(deserializer);
    var var_draftText = sse_decode_String(deserializer);
    var var_draftTextTime = sse_decode_i_64(deserializer);
    var var_maxSeq = sse_decode_i_64(deserializer);
    var var_minSeq = sse_decode_i_64(deserializer);
    var var_isMsgDestruct = sse_decode_bool(deserializer);
    var var_msgDestructTime = sse_decode_i_64(deserializer);
    return LocalConversation(
      conversationId: var_conversationId,
      conversationType: var_conversationType,
      userId: var_userId,
      groupId: var_groupId,
      showName: var_showName,
      faceUrl: var_faceUrl,
      latestMsg: var_latestMsg,
      latestMsgSendTime: var_latestMsgSendTime,
      unreadCount: var_unreadCount,
      recvMsgOpt: var_recvMsgOpt,
      isPinned: var_isPinned,
      isPrivateChat: var_isPrivateChat,
      burnDuration: var_burnDuration,
      groupAtType: var_groupAtType,
      isNotInGroup: var_isNotInGroup,
      updateUnreadCountTime: var_updateUnreadCountTime,
      attachedInfo: var_attachedInfo,
      ex: var_ex,
      draftText: var_draftText,
      draftTextTime: var_draftTextTime,
      maxSeq: var_maxSeq,
      minSeq: var_minSeq,
      isMsgDestruct: var_isMsgDestruct,
      msgDestructTime: var_msgDestructTime,
    );
  }

  @protected
  LoggerConfig sse_decode_logger_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_logLevel = sse_decode_String(deserializer);
    var var_logFilePath = sse_decode_String(deserializer);
    var var_isLogStandardOutput = sse_decode_bool(deserializer);
    return LoggerConfig(
      logLevel: var_logLevel,
      logFilePath: var_logFilePath,
      isLogStandardOutput: var_isLogStandardOutput,
    );
  }

  @protected
  LoginData sse_decode_login_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_imToken = sse_decode_String(deserializer);
    var var_chatToken = sse_decode_String(deserializer);
    var var_userId = sse_decode_String(deserializer);
    return LoginData(
      imToken: var_imToken,
      chatToken: var_chatToken,
      userId: var_userId,
    );
  }

  @protected
  LoginResponse sse_decode_login_response(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_errCode = sse_decode_i_32(deserializer);
    var var_errMsg = sse_decode_String(deserializer);
    var var_data = sse_decode_opt_box_autoadd_login_data(deserializer);
    return LoginResponse(
      errCode: var_errCode,
      errMsg: var_errMsg,
      data: var_data,
    );
  }

  @protected
  MessageEvent sse_decode_message_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_message = sse_decode_String(deserializer);
    return MessageEvent(message: var_message);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  LoginData? sse_decode_opt_box_autoadd_login_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_login_data(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
    OpenImBridgeClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as OpenImBridgeClientImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
    OpenImBridgeClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as OpenImBridgeClientImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
    OpenImBridgeClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as OpenImBridgeClientImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
    OpenImBridgeClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as OpenImBridgeClientImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_conversation_changed_event_Sse(
    RustStreamSink<ConversationChangedEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_conversation_changed_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_message_event_Sse(
    RustStreamSink<MessageEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_message_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_logger_config(
    LoggerConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_logger_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_login_data(
    LoginData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_login_data(self, serializer);
  }

  @protected
  void sse_encode_conversation_changed_event(
    ConversationChangedEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.conversationList, serializer);
  }

  @protected
  void sse_encode_dart_advanced_msg_listener(
    DartAdvancedMsgListener self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_StreamSink_message_event_Sse(self.messageSink, serializer);
  }

  @protected
  void sse_encode_dart_conversation_listener(
    DartConversationListener self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_StreamSink_conversation_changed_event_Sse(self.sink, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_local_conversation(
    List<LocalConversation> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_local_conversation(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_local_conversation(
    LocalConversation self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.conversationId, serializer);
    sse_encode_i_32(self.conversationType, serializer);
    sse_encode_String(self.userId, serializer);
    sse_encode_String(self.groupId, serializer);
    sse_encode_String(self.showName, serializer);
    sse_encode_String(self.faceUrl, serializer);
    sse_encode_String(self.latestMsg, serializer);
    sse_encode_i_64(self.latestMsgSendTime, serializer);
    sse_encode_i_32(self.unreadCount, serializer);
    sse_encode_i_32(self.recvMsgOpt, serializer);
    sse_encode_bool(self.isPinned, serializer);
    sse_encode_bool(self.isPrivateChat, serializer);
    sse_encode_i_32(self.burnDuration, serializer);
    sse_encode_i_32(self.groupAtType, serializer);
    sse_encode_bool(self.isNotInGroup, serializer);
    sse_encode_i_64(self.updateUnreadCountTime, serializer);
    sse_encode_String(self.attachedInfo, serializer);
    sse_encode_String(self.ex, serializer);
    sse_encode_String(self.draftText, serializer);
    sse_encode_i_64(self.draftTextTime, serializer);
    sse_encode_i_64(self.maxSeq, serializer);
    sse_encode_i_64(self.minSeq, serializer);
    sse_encode_bool(self.isMsgDestruct, serializer);
    sse_encode_i_64(self.msgDestructTime, serializer);
  }

  @protected
  void sse_encode_logger_config(LoggerConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.logLevel, serializer);
    sse_encode_String(self.logFilePath, serializer);
    sse_encode_bool(self.isLogStandardOutput, serializer);
  }

  @protected
  void sse_encode_login_data(LoginData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.imToken, serializer);
    sse_encode_String(self.chatToken, serializer);
    sse_encode_String(self.userId, serializer);
  }

  @protected
  void sse_encode_login_response(LoginResponse self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.errCode, serializer);
    sse_encode_String(self.errMsg, serializer);
    sse_encode_opt_box_autoadd_login_data(self.data, serializer);
  }

  @protected
  void sse_encode_message_event(MessageEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_login_data(
    LoginData? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_login_data(self, serializer);
    }
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class OpenImBridgeClientImpl extends RustOpaque implements OpenImBridgeClient {
  // Not to be used by end users
  OpenImBridgeClientImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  OpenImBridgeClientImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_OpenImBridgeClient,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_OpenImBridgeClient,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_OpenImBridgeClientPtr,
  );

  /// 连接到服务器
  ///
  /// 建立 WebSocket 连接并启动消息监听。
  /// 连接成功后会自动启动心跳和消息处理任务。
  Future<void> connect() => RustLib.instance.api
      .crateApiBridgeClientOpenImBridgeClientConnect(that: this);

  /// 设置会话监听器
  ///
  /// 监听会话变更事件，通过 StreamSink 发送到 Dart
  Stream<ConversationChangedEvent> conversationEvent() => RustLib.instance.api
      .crateApiBridgeClientOpenImBridgeClientConversationEvent(that: this);

  /// 获取所有会话列表
  Future<List<LocalConversation>> getAllConversations() => RustLib.instance.api
      .crateApiBridgeClientOpenImBridgeClientGetAllConversations(that: this);

  /// 设置消息监听器
  ///
  /// 监听消息和连接状态事件，通过 StreamSink 发送到 Dart
  Stream<MessageEvent> messageEvent() => RustLib.instance.api
      .crateApiBridgeClientOpenImBridgeClientMessageEvent(that: this);
}
