// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/client.dart';
import 'api/ffi_init.dart';
import 'api/global.dart';
import 'api/message.dart';
import 'api/message_advanced.dart';
import 'api/message_media.dart';
import 'core/connection/manager.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'domain/constant/enums.dart';
import 'domain/model/friend.dart';
import 'domain/model/group.dart';
import 'domain/model/local.dart';
import 'domain/model/message.dart';
import 'domain/model/msg_struct.dart';
import 'domain/model/user.dart';
import 'domain/ports/friend.dart';
import 'domain/ports/group.dart';
import 'domain/ports/message.dart';
import 'domain/ports/online.dart';
import 'event/events/connection.dart';
import 'event/events/conversation.dart';
import 'event/events/friend.dart';
import 'event/events/group.dart';
import 'event/events/message.dart';
import 'frb_generated.dart';
import 'infra/logger/config.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'sdk/client/types.dart';
import 'sdk/config.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_OpenImBridgeClientPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClientPtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  OpenImBridgeClient
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
    dynamic raw,
  );

  @protected
  OpenImBridgeClient
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
    dynamic raw,
  );

  @protected
  OpenImBridgeClient
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
    dynamic raw,
  );

  @protected
  RustStreamSink<ConnectionEvent> dco_decode_StreamSink_connection_event_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<ConversationEvent>
  dco_decode_StreamSink_conversation_event_Sse(dynamic raw);

  @protected
  RustStreamSink<FriendEvent> dco_decode_StreamSink_friend_event_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<GroupEvent> dco_decode_StreamSink_group_event_Sse(dynamic raw);

  @protected
  RustStreamSink<int> dco_decode_StreamSink_i_32_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AdvancedTextElem dco_decode_advanced_text_elem(dynamic raw);

  @protected
  AtInfo dco_decode_at_info(dynamic raw);

  @protected
  AtTextElem dco_decode_at_text_elem(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AdvancedTextElem dco_decode_box_autoadd_advanced_text_elem(dynamic raw);

  @protected
  AtTextElem dco_decode_box_autoadd_at_text_elem(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  CardElem dco_decode_box_autoadd_card_elem(dynamic raw);

  @protected
  ClientConfig dco_decode_box_autoadd_client_config(dynamic raw);

  @protected
  CustomElem dco_decode_box_autoadd_custom_elem(dynamic raw);

  @protected
  DeleteMessagesReq dco_decode_box_autoadd_delete_messages_req(dynamic raw);

  @protected
  FaceElem dco_decode_box_autoadd_face_elem(dynamic raw);

  @protected
  FileElem dco_decode_box_autoadd_file_elem(dynamic raw);

  @protected
  GetHistoryMessagesReq dco_decode_box_autoadd_get_history_messages_req(
    dynamic raw,
  );

  @protected
  GroupInfo dco_decode_box_autoadd_group_info(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  LocalConversation dco_decode_box_autoadd_local_conversation(dynamic raw);

  @protected
  LocationElem dco_decode_box_autoadd_location_elem(dynamic raw);

  @protected
  LogConfig dco_decode_box_autoadd_log_config(dynamic raw);

  @protected
  MarkMessagesAsReadReq dco_decode_box_autoadd_mark_messages_as_read_req(
    dynamic raw,
  );

  @protected
  MarkdownTextElem dco_decode_box_autoadd_markdown_text_elem(dynamic raw);

  @protected
  MergeElem dco_decode_box_autoadd_merge_elem(dynamic raw);

  @protected
  MsgStruct dco_decode_box_autoadd_msg_struct(dynamic raw);

  @protected
  OfflinePushInfo dco_decode_box_autoadd_offline_push_info(dynamic raw);

  @protected
  PictureElem dco_decode_box_autoadd_picture_elem(dynamic raw);

  @protected
  QuoteElem dco_decode_box_autoadd_quote_elem(dynamic raw);

  @protected
  RevokeMessageReq dco_decode_box_autoadd_revoke_message_req(dynamic raw);

  @protected
  SearchMessagesReq dco_decode_box_autoadd_search_messages_req(dynamic raw);

  @protected
  SoundElem dco_decode_box_autoadd_sound_elem(dynamic raw);

  @protected
  TextElem dco_decode_box_autoadd_text_elem(dynamic raw);

  @protected
  VideoElem dco_decode_box_autoadd_video_elem(dynamic raw);

  @protected
  MsgStruct dco_decode_box_msg_struct(dynamic raw);

  @protected
  CardElem dco_decode_card_elem(dynamic raw);

  @protected
  CheckFriendResult dco_decode_check_friend_result(dynamic raw);

  @protected
  ClientConfig dco_decode_client_config(dynamic raw);

  @protected
  ConnectionEvent dco_decode_connection_event(dynamic raw);

  @protected
  ConnectionState dco_decode_connection_state(dynamic raw);

  @protected
  ConversationEvent dco_decode_conversation_event(dynamic raw);

  @protected
  CustomElem dco_decode_custom_elem(dynamic raw);

  @protected
  DeleteMessagesReq dco_decode_delete_messages_req(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FaceElem dco_decode_face_elem(dynamic raw);

  @protected
  FileElem dco_decode_file_elem(dynamic raw);

  @protected
  FriendApplyInfo dco_decode_friend_apply_info(dynamic raw);

  @protected
  FriendEvent dco_decode_friend_event(dynamic raw);

  @protected
  FriendInfo dco_decode_friend_info(dynamic raw);

  @protected
  GetHistoryMessagesReq dco_decode_get_history_messages_req(dynamic raw);

  @protected
  GetHistoryMessagesResult dco_decode_get_history_messages_result(dynamic raw);

  @protected
  GroupApplyInfo dco_decode_group_apply_info(dynamic raw);

  @protected
  GroupEvent dco_decode_group_event(dynamic raw);

  @protected
  GroupInfo dco_decode_group_info(dynamic raw);

  @protected
  GroupMember dco_decode_group_member(dynamic raw);

  @protected
  GroupReadReceipt dco_decode_group_read_receipt(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AtInfo> dco_decode_list_at_info(dynamic raw);

  @protected
  List<CheckFriendResult> dco_decode_list_check_friend_result(dynamic raw);

  @protected
  List<FriendApplyInfo> dco_decode_list_friend_apply_info(dynamic raw);

  @protected
  List<FriendInfo> dco_decode_list_friend_info(dynamic raw);

  @protected
  List<GroupApplyInfo> dco_decode_list_group_apply_info(dynamic raw);

  @protected
  List<GroupInfo> dco_decode_list_group_info(dynamic raw);

  @protected
  List<GroupMember> dco_decode_list_group_member(dynamic raw);

  @protected
  List<GroupReadReceipt> dco_decode_list_group_read_receipt(dynamic raw);

  @protected
  List<LocalChatLog> dco_decode_list_local_chat_log(dynamic raw);

  @protected
  List<LocalConversation> dco_decode_list_local_conversation(dynamic raw);

  @protected
  List<MessageEntity> dco_decode_list_message_entity(dynamic raw);

  @protected
  List<MessageInfo> dco_decode_list_message_info(dynamic raw);

  @protected
  List<MsgStruct> dco_decode_list_msg_struct(dynamic raw);

  @protected
  List<OnlineStatus> dco_decode_list_online_status(dynamic raw);

  @protected
  Int32List dco_decode_list_prim_i_32_strict(dynamic raw);

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SearchFriendItem> dco_decode_list_search_friend_item(dynamic raw);

  @protected
  List<UserInfo> dco_decode_list_user_info(dynamic raw);

  @protected
  LocalChatLog dco_decode_local_chat_log(dynamic raw);

  @protected
  LocalConversation dco_decode_local_conversation(dynamic raw);

  @protected
  LocationElem dco_decode_location_elem(dynamic raw);

  @protected
  LogConfig dco_decode_log_config(dynamic raw);

  @protected
  MarkMessagesAsReadReq dco_decode_mark_messages_as_read_req(dynamic raw);

  @protected
  MarkdownTextElem dco_decode_markdown_text_elem(dynamic raw);

  @protected
  MergeElem dco_decode_merge_elem(dynamic raw);

  @protected
  MessageEntity dco_decode_message_entity(dynamic raw);

  @protected
  MessageInfo dco_decode_message_info(dynamic raw);

  @protected
  MsgStruct dco_decode_msg_struct(dynamic raw);

  @protected
  OfflinePushInfo dco_decode_offline_push_info(dynamic raw);

  @protected
  OnlineStatus dco_decode_online_status(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  AdvancedTextElem? dco_decode_opt_box_autoadd_advanced_text_elem(dynamic raw);

  @protected
  AtTextElem? dco_decode_opt_box_autoadd_at_text_elem(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  CardElem? dco_decode_opt_box_autoadd_card_elem(dynamic raw);

  @protected
  CustomElem? dco_decode_opt_box_autoadd_custom_elem(dynamic raw);

  @protected
  FaceElem? dco_decode_opt_box_autoadd_face_elem(dynamic raw);

  @protected
  FileElem? dco_decode_opt_box_autoadd_file_elem(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  LocalConversation? dco_decode_opt_box_autoadd_local_conversation(dynamic raw);

  @protected
  LocationElem? dco_decode_opt_box_autoadd_location_elem(dynamic raw);

  @protected
  MarkdownTextElem? dco_decode_opt_box_autoadd_markdown_text_elem(dynamic raw);

  @protected
  MergeElem? dco_decode_opt_box_autoadd_merge_elem(dynamic raw);

  @protected
  OfflinePushInfo? dco_decode_opt_box_autoadd_offline_push_info(dynamic raw);

  @protected
  PictureElem? dco_decode_opt_box_autoadd_picture_elem(dynamic raw);

  @protected
  QuoteElem? dco_decode_opt_box_autoadd_quote_elem(dynamic raw);

  @protected
  SoundElem? dco_decode_opt_box_autoadd_sound_elem(dynamic raw);

  @protected
  TextElem? dco_decode_opt_box_autoadd_text_elem(dynamic raw);

  @protected
  VideoElem? dco_decode_opt_box_autoadd_video_elem(dynamic raw);

  @protected
  MsgStruct? dco_decode_opt_box_msg_struct(dynamic raw);

  @protected
  PictureBaseInfo dco_decode_picture_base_info(dynamic raw);

  @protected
  PictureElem dco_decode_picture_elem(dynamic raw);

  @protected
  QuoteElem dco_decode_quote_elem(dynamic raw);

  @protected
  RevokeMessageReq dco_decode_revoke_message_req(dynamic raw);

  @protected
  SearchFriendItem dco_decode_search_friend_item(dynamic raw);

  @protected
  SearchMessagesReq dco_decode_search_messages_req(dynamic raw);

  @protected
  SendTypingResp dco_decode_send_typing_resp(dynamic raw);

  @protected
  SessionType dco_decode_session_type(dynamic raw);

  @protected
  SoundElem dco_decode_sound_elem(dynamic raw);

  @protected
  TextElem dco_decode_text_elem(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UserInfo dco_decode_user_info(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  VideoElem dco_decode_video_elem(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  OpenImBridgeClient
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
    SseDeserializer deserializer,
  );

  @protected
  OpenImBridgeClient
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
    SseDeserializer deserializer,
  );

  @protected
  OpenImBridgeClient
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ConnectionEvent> sse_decode_StreamSink_connection_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ConversationEvent>
  sse_decode_StreamSink_conversation_event_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<FriendEvent> sse_decode_StreamSink_friend_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<GroupEvent> sse_decode_StreamSink_group_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<int> sse_decode_StreamSink_i_32_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AdvancedTextElem sse_decode_advanced_text_elem(SseDeserializer deserializer);

  @protected
  AtInfo sse_decode_at_info(SseDeserializer deserializer);

  @protected
  AtTextElem sse_decode_at_text_elem(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AdvancedTextElem sse_decode_box_autoadd_advanced_text_elem(
    SseDeserializer deserializer,
  );

  @protected
  AtTextElem sse_decode_box_autoadd_at_text_elem(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  CardElem sse_decode_box_autoadd_card_elem(SseDeserializer deserializer);

  @protected
  ClientConfig sse_decode_box_autoadd_client_config(
    SseDeserializer deserializer,
  );

  @protected
  CustomElem sse_decode_box_autoadd_custom_elem(SseDeserializer deserializer);

  @protected
  DeleteMessagesReq sse_decode_box_autoadd_delete_messages_req(
    SseDeserializer deserializer,
  );

  @protected
  FaceElem sse_decode_box_autoadd_face_elem(SseDeserializer deserializer);

  @protected
  FileElem sse_decode_box_autoadd_file_elem(SseDeserializer deserializer);

  @protected
  GetHistoryMessagesReq sse_decode_box_autoadd_get_history_messages_req(
    SseDeserializer deserializer,
  );

  @protected
  GroupInfo sse_decode_box_autoadd_group_info(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  LocalConversation sse_decode_box_autoadd_local_conversation(
    SseDeserializer deserializer,
  );

  @protected
  LocationElem sse_decode_box_autoadd_location_elem(
    SseDeserializer deserializer,
  );

  @protected
  LogConfig sse_decode_box_autoadd_log_config(SseDeserializer deserializer);

  @protected
  MarkMessagesAsReadReq sse_decode_box_autoadd_mark_messages_as_read_req(
    SseDeserializer deserializer,
  );

  @protected
  MarkdownTextElem sse_decode_box_autoadd_markdown_text_elem(
    SseDeserializer deserializer,
  );

  @protected
  MergeElem sse_decode_box_autoadd_merge_elem(SseDeserializer deserializer);

  @protected
  MsgStruct sse_decode_box_autoadd_msg_struct(SseDeserializer deserializer);

  @protected
  OfflinePushInfo sse_decode_box_autoadd_offline_push_info(
    SseDeserializer deserializer,
  );

  @protected
  PictureElem sse_decode_box_autoadd_picture_elem(SseDeserializer deserializer);

  @protected
  QuoteElem sse_decode_box_autoadd_quote_elem(SseDeserializer deserializer);

  @protected
  RevokeMessageReq sse_decode_box_autoadd_revoke_message_req(
    SseDeserializer deserializer,
  );

  @protected
  SearchMessagesReq sse_decode_box_autoadd_search_messages_req(
    SseDeserializer deserializer,
  );

  @protected
  SoundElem sse_decode_box_autoadd_sound_elem(SseDeserializer deserializer);

  @protected
  TextElem sse_decode_box_autoadd_text_elem(SseDeserializer deserializer);

  @protected
  VideoElem sse_decode_box_autoadd_video_elem(SseDeserializer deserializer);

  @protected
  MsgStruct sse_decode_box_msg_struct(SseDeserializer deserializer);

  @protected
  CardElem sse_decode_card_elem(SseDeserializer deserializer);

  @protected
  CheckFriendResult sse_decode_check_friend_result(
    SseDeserializer deserializer,
  );

  @protected
  ClientConfig sse_decode_client_config(SseDeserializer deserializer);

  @protected
  ConnectionEvent sse_decode_connection_event(SseDeserializer deserializer);

  @protected
  ConnectionState sse_decode_connection_state(SseDeserializer deserializer);

  @protected
  ConversationEvent sse_decode_conversation_event(SseDeserializer deserializer);

  @protected
  CustomElem sse_decode_custom_elem(SseDeserializer deserializer);

  @protected
  DeleteMessagesReq sse_decode_delete_messages_req(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FaceElem sse_decode_face_elem(SseDeserializer deserializer);

  @protected
  FileElem sse_decode_file_elem(SseDeserializer deserializer);

  @protected
  FriendApplyInfo sse_decode_friend_apply_info(SseDeserializer deserializer);

  @protected
  FriendEvent sse_decode_friend_event(SseDeserializer deserializer);

  @protected
  FriendInfo sse_decode_friend_info(SseDeserializer deserializer);

  @protected
  GetHistoryMessagesReq sse_decode_get_history_messages_req(
    SseDeserializer deserializer,
  );

  @protected
  GetHistoryMessagesResult sse_decode_get_history_messages_result(
    SseDeserializer deserializer,
  );

  @protected
  GroupApplyInfo sse_decode_group_apply_info(SseDeserializer deserializer);

  @protected
  GroupEvent sse_decode_group_event(SseDeserializer deserializer);

  @protected
  GroupInfo sse_decode_group_info(SseDeserializer deserializer);

  @protected
  GroupMember sse_decode_group_member(SseDeserializer deserializer);

  @protected
  GroupReadReceipt sse_decode_group_read_receipt(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AtInfo> sse_decode_list_at_info(SseDeserializer deserializer);

  @protected
  List<CheckFriendResult> sse_decode_list_check_friend_result(
    SseDeserializer deserializer,
  );

  @protected
  List<FriendApplyInfo> sse_decode_list_friend_apply_info(
    SseDeserializer deserializer,
  );

  @protected
  List<FriendInfo> sse_decode_list_friend_info(SseDeserializer deserializer);

  @protected
  List<GroupApplyInfo> sse_decode_list_group_apply_info(
    SseDeserializer deserializer,
  );

  @protected
  List<GroupInfo> sse_decode_list_group_info(SseDeserializer deserializer);

  @protected
  List<GroupMember> sse_decode_list_group_member(SseDeserializer deserializer);

  @protected
  List<GroupReadReceipt> sse_decode_list_group_read_receipt(
    SseDeserializer deserializer,
  );

  @protected
  List<LocalChatLog> sse_decode_list_local_chat_log(
    SseDeserializer deserializer,
  );

  @protected
  List<LocalConversation> sse_decode_list_local_conversation(
    SseDeserializer deserializer,
  );

  @protected
  List<MessageEntity> sse_decode_list_message_entity(
    SseDeserializer deserializer,
  );

  @protected
  List<MessageInfo> sse_decode_list_message_info(SseDeserializer deserializer);

  @protected
  List<MsgStruct> sse_decode_list_msg_struct(SseDeserializer deserializer);

  @protected
  List<OnlineStatus> sse_decode_list_online_status(
    SseDeserializer deserializer,
  );

  @protected
  Int32List sse_decode_list_prim_i_32_strict(SseDeserializer deserializer);

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SearchFriendItem> sse_decode_list_search_friend_item(
    SseDeserializer deserializer,
  );

  @protected
  List<UserInfo> sse_decode_list_user_info(SseDeserializer deserializer);

  @protected
  LocalChatLog sse_decode_local_chat_log(SseDeserializer deserializer);

  @protected
  LocalConversation sse_decode_local_conversation(SseDeserializer deserializer);

  @protected
  LocationElem sse_decode_location_elem(SseDeserializer deserializer);

  @protected
  LogConfig sse_decode_log_config(SseDeserializer deserializer);

  @protected
  MarkMessagesAsReadReq sse_decode_mark_messages_as_read_req(
    SseDeserializer deserializer,
  );

  @protected
  MarkdownTextElem sse_decode_markdown_text_elem(SseDeserializer deserializer);

  @protected
  MergeElem sse_decode_merge_elem(SseDeserializer deserializer);

  @protected
  MessageEntity sse_decode_message_entity(SseDeserializer deserializer);

  @protected
  MessageInfo sse_decode_message_info(SseDeserializer deserializer);

  @protected
  MsgStruct sse_decode_msg_struct(SseDeserializer deserializer);

  @protected
  OfflinePushInfo sse_decode_offline_push_info(SseDeserializer deserializer);

  @protected
  OnlineStatus sse_decode_online_status(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  AdvancedTextElem? sse_decode_opt_box_autoadd_advanced_text_elem(
    SseDeserializer deserializer,
  );

  @protected
  AtTextElem? sse_decode_opt_box_autoadd_at_text_elem(
    SseDeserializer deserializer,
  );

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  CardElem? sse_decode_opt_box_autoadd_card_elem(SseDeserializer deserializer);

  @protected
  CustomElem? sse_decode_opt_box_autoadd_custom_elem(
    SseDeserializer deserializer,
  );

  @protected
  FaceElem? sse_decode_opt_box_autoadd_face_elem(SseDeserializer deserializer);

  @protected
  FileElem? sse_decode_opt_box_autoadd_file_elem(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  LocalConversation? sse_decode_opt_box_autoadd_local_conversation(
    SseDeserializer deserializer,
  );

  @protected
  LocationElem? sse_decode_opt_box_autoadd_location_elem(
    SseDeserializer deserializer,
  );

  @protected
  MarkdownTextElem? sse_decode_opt_box_autoadd_markdown_text_elem(
    SseDeserializer deserializer,
  );

  @protected
  MergeElem? sse_decode_opt_box_autoadd_merge_elem(
    SseDeserializer deserializer,
  );

  @protected
  OfflinePushInfo? sse_decode_opt_box_autoadd_offline_push_info(
    SseDeserializer deserializer,
  );

  @protected
  PictureElem? sse_decode_opt_box_autoadd_picture_elem(
    SseDeserializer deserializer,
  );

  @protected
  QuoteElem? sse_decode_opt_box_autoadd_quote_elem(
    SseDeserializer deserializer,
  );

  @protected
  SoundElem? sse_decode_opt_box_autoadd_sound_elem(
    SseDeserializer deserializer,
  );

  @protected
  TextElem? sse_decode_opt_box_autoadd_text_elem(SseDeserializer deserializer);

  @protected
  VideoElem? sse_decode_opt_box_autoadd_video_elem(
    SseDeserializer deserializer,
  );

  @protected
  MsgStruct? sse_decode_opt_box_msg_struct(SseDeserializer deserializer);

  @protected
  PictureBaseInfo sse_decode_picture_base_info(SseDeserializer deserializer);

  @protected
  PictureElem sse_decode_picture_elem(SseDeserializer deserializer);

  @protected
  QuoteElem sse_decode_quote_elem(SseDeserializer deserializer);

  @protected
  RevokeMessageReq sse_decode_revoke_message_req(SseDeserializer deserializer);

  @protected
  SearchFriendItem sse_decode_search_friend_item(SseDeserializer deserializer);

  @protected
  SearchMessagesReq sse_decode_search_messages_req(
    SseDeserializer deserializer,
  );

  @protected
  SendTypingResp sse_decode_send_typing_resp(SseDeserializer deserializer);

  @protected
  SessionType sse_decode_session_type(SseDeserializer deserializer);

  @protected
  SoundElem sse_decode_sound_elem(SseDeserializer deserializer);

  @protected
  TextElem sse_decode_text_elem(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UserInfo sse_decode_user_info(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  VideoElem sse_decode_video_elem(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
    OpenImBridgeClient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
    OpenImBridgeClient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
    OpenImBridgeClient self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_connection_event_Sse(
    RustStreamSink<ConnectionEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_conversation_event_Sse(
    RustStreamSink<ConversationEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_friend_event_Sse(
    RustStreamSink<FriendEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_group_event_Sse(
    RustStreamSink<GroupEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_i_32_Sse(
    RustStreamSink<int> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_advanced_text_elem(
    AdvancedTextElem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_at_info(AtInfo self, SseSerializer serializer);

  @protected
  void sse_encode_at_text_elem(AtTextElem self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_advanced_text_elem(
    AdvancedTextElem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_at_text_elem(
    AtTextElem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_card_elem(
    CardElem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_client_config(
    ClientConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_custom_elem(
    CustomElem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_delete_messages_req(
    DeleteMessagesReq self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_face_elem(
    FaceElem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_file_elem(
    FileElem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_get_history_messages_req(
    GetHistoryMessagesReq self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_group_info(
    GroupInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_local_conversation(
    LocalConversation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_location_elem(
    LocationElem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_log_config(
    LogConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_mark_messages_as_read_req(
    MarkMessagesAsReadReq self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_markdown_text_elem(
    MarkdownTextElem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_merge_elem(
    MergeElem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_msg_struct(
    MsgStruct self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_offline_push_info(
    OfflinePushInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_picture_elem(
    PictureElem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_quote_elem(
    QuoteElem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_revoke_message_req(
    RevokeMessageReq self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_search_messages_req(
    SearchMessagesReq self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_sound_elem(
    SoundElem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_text_elem(
    TextElem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_video_elem(
    VideoElem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_msg_struct(MsgStruct self, SseSerializer serializer);

  @protected
  void sse_encode_card_elem(CardElem self, SseSerializer serializer);

  @protected
  void sse_encode_check_friend_result(
    CheckFriendResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_client_config(ClientConfig self, SseSerializer serializer);

  @protected
  void sse_encode_connection_event(
    ConnectionEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_connection_state(
    ConnectionState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_conversation_event(
    ConversationEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_custom_elem(CustomElem self, SseSerializer serializer);

  @protected
  void sse_encode_delete_messages_req(
    DeleteMessagesReq self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_face_elem(FaceElem self, SseSerializer serializer);

  @protected
  void sse_encode_file_elem(FileElem self, SseSerializer serializer);

  @protected
  void sse_encode_friend_apply_info(
    FriendApplyInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_friend_event(FriendEvent self, SseSerializer serializer);

  @protected
  void sse_encode_friend_info(FriendInfo self, SseSerializer serializer);

  @protected
  void sse_encode_get_history_messages_req(
    GetHistoryMessagesReq self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_get_history_messages_result(
    GetHistoryMessagesResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_group_apply_info(
    GroupApplyInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_group_event(GroupEvent self, SseSerializer serializer);

  @protected
  void sse_encode_group_info(GroupInfo self, SseSerializer serializer);

  @protected
  void sse_encode_group_member(GroupMember self, SseSerializer serializer);

  @protected
  void sse_encode_group_read_receipt(
    GroupReadReceipt self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_at_info(List<AtInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_check_friend_result(
    List<CheckFriendResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_friend_apply_info(
    List<FriendApplyInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_friend_info(
    List<FriendInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_group_apply_info(
    List<GroupApplyInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_group_info(
    List<GroupInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_group_member(
    List<GroupMember> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_group_read_receipt(
    List<GroupReadReceipt> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_local_chat_log(
    List<LocalChatLog> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_local_conversation(
    List<LocalConversation> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_message_entity(
    List<MessageEntity> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_message_info(
    List<MessageInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_msg_struct(
    List<MsgStruct> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_online_status(
    List<OnlineStatus> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_32_strict(
    Int32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_64_strict(
    Int64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_search_friend_item(
    List<SearchFriendItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_user_info(List<UserInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_local_chat_log(LocalChatLog self, SseSerializer serializer);

  @protected
  void sse_encode_local_conversation(
    LocalConversation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_location_elem(LocationElem self, SseSerializer serializer);

  @protected
  void sse_encode_log_config(LogConfig self, SseSerializer serializer);

  @protected
  void sse_encode_mark_messages_as_read_req(
    MarkMessagesAsReadReq self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_markdown_text_elem(
    MarkdownTextElem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_merge_elem(MergeElem self, SseSerializer serializer);

  @protected
  void sse_encode_message_entity(MessageEntity self, SseSerializer serializer);

  @protected
  void sse_encode_message_info(MessageInfo self, SseSerializer serializer);

  @protected
  void sse_encode_msg_struct(MsgStruct self, SseSerializer serializer);

  @protected
  void sse_encode_offline_push_info(
    OfflinePushInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_online_status(OnlineStatus self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_advanced_text_elem(
    AdvancedTextElem? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_at_text_elem(
    AtTextElem? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_card_elem(
    CardElem? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_custom_elem(
    CustomElem? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_face_elem(
    FaceElem? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_file_elem(
    FileElem? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_local_conversation(
    LocalConversation? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_location_elem(
    LocationElem? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_markdown_text_elem(
    MarkdownTextElem? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_merge_elem(
    MergeElem? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_offline_push_info(
    OfflinePushInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_picture_elem(
    PictureElem? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_quote_elem(
    QuoteElem? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_sound_elem(
    SoundElem? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_text_elem(
    TextElem? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_video_elem(
    VideoElem? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_msg_struct(MsgStruct? self, SseSerializer serializer);

  @protected
  void sse_encode_picture_base_info(
    PictureBaseInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_picture_elem(PictureElem self, SseSerializer serializer);

  @protected
  void sse_encode_quote_elem(QuoteElem self, SseSerializer serializer);

  @protected
  void sse_encode_revoke_message_req(
    RevokeMessageReq self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_search_friend_item(
    SearchFriendItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_search_messages_req(
    SearchMessagesReq self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_send_typing_resp(
    SendTypingResp self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_session_type(SessionType self, SseSerializer serializer);

  @protected
  void sse_encode_sound_elem(SoundElem self, SseSerializer serializer);

  @protected
  void sse_encode_text_elem(TextElem self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_user_info(UserInfo self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_video_elem(VideoElem self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClientPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_flutter_rust_demo_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClientPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClientPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_flutter_rust_demo_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClientPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
