// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/bridge_client.dart';
import 'api/listeners.dart';
import 'api/logger.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'im/auth.dart';
import 'im/types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_OpenImBridgeClientPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  OpenImBridgeClient
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
    dynamic raw,
  );

  @protected
  OpenImBridgeClient
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
    dynamic raw,
  );

  @protected
  OpenImBridgeClient
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
    dynamic raw,
  );

  @protected
  OpenImBridgeClient
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
    dynamic raw,
  );

  @protected
  RustStreamSink<ConversationChangedEvent>
  dco_decode_StreamSink_conversation_changed_event_Sse(dynamic raw);

  @protected
  RustStreamSink<MessageEvent> dco_decode_StreamSink_message_event_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  LoggerConfig dco_decode_box_autoadd_logger_config(dynamic raw);

  @protected
  LoginData dco_decode_box_autoadd_login_data(dynamic raw);

  @protected
  ConversationChangedEvent dco_decode_conversation_changed_event(dynamic raw);

  @protected
  DartAdvancedMsgListener dco_decode_dart_advanced_msg_listener(dynamic raw);

  @protected
  DartConversationListener dco_decode_dart_conversation_listener(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<LocalConversation> dco_decode_list_local_conversation(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  LocalConversation dco_decode_local_conversation(dynamic raw);

  @protected
  LoggerConfig dco_decode_logger_config(dynamic raw);

  @protected
  LoginData dco_decode_login_data(dynamic raw);

  @protected
  LoginResponse dco_decode_login_response(dynamic raw);

  @protected
  MessageEvent dco_decode_message_event(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  LoginData? dco_decode_opt_box_autoadd_login_data(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  OpenImBridgeClient
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
    SseDeserializer deserializer,
  );

  @protected
  OpenImBridgeClient
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
    SseDeserializer deserializer,
  );

  @protected
  OpenImBridgeClient
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
    SseDeserializer deserializer,
  );

  @protected
  OpenImBridgeClient
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ConversationChangedEvent>
  sse_decode_StreamSink_conversation_changed_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<MessageEvent> sse_decode_StreamSink_message_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  LoggerConfig sse_decode_box_autoadd_logger_config(
    SseDeserializer deserializer,
  );

  @protected
  LoginData sse_decode_box_autoadd_login_data(SseDeserializer deserializer);

  @protected
  ConversationChangedEvent sse_decode_conversation_changed_event(
    SseDeserializer deserializer,
  );

  @protected
  DartAdvancedMsgListener sse_decode_dart_advanced_msg_listener(
    SseDeserializer deserializer,
  );

  @protected
  DartConversationListener sse_decode_dart_conversation_listener(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<LocalConversation> sse_decode_list_local_conversation(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  LocalConversation sse_decode_local_conversation(SseDeserializer deserializer);

  @protected
  LoggerConfig sse_decode_logger_config(SseDeserializer deserializer);

  @protected
  LoginData sse_decode_login_data(SseDeserializer deserializer);

  @protected
  LoginResponse sse_decode_login_response(SseDeserializer deserializer);

  @protected
  MessageEvent sse_decode_message_event(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  LoginData? sse_decode_opt_box_autoadd_login_data(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
    OpenImBridgeClient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
    OpenImBridgeClient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
    OpenImBridgeClient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
    OpenImBridgeClient self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_conversation_changed_event_Sse(
    RustStreamSink<ConversationChangedEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_message_event_Sse(
    RustStreamSink<MessageEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_logger_config(
    LoggerConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_login_data(
    LoginData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_conversation_changed_event(
    ConversationChangedEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_dart_advanced_msg_listener(
    DartAdvancedMsgListener self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_dart_conversation_listener(
    DartConversationListener self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_local_conversation(
    List<LocalConversation> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_local_conversation(
    LocalConversation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_logger_config(LoggerConfig self, SseSerializer serializer);

  @protected
  void sse_encode_login_data(LoginData self, SseSerializer serializer);

  @protected
  void sse_encode_login_response(LoginResponse self, SseSerializer serializer);

  @protected
  void sse_encode_message_event(MessageEvent self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_login_data(
    LoginData? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOpenIMBridgeClient(
    int ptr,
  );
}
