// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 本地好友数据结构（与 Go 的 LocalFriend 字段基本对应）
class LocalFriend {
  final String ownerUserId;
  final String friendUserId;
  final String remark;
  final PlatformInt64 createTime;
  final int addSource;
  final String operatorUserId;
  final String nickname;
  final String faceUrl;
  final String ex;
  final String attachedInfo;
  final bool isPinned;

  const LocalFriend({
    required this.ownerUserId,
    required this.friendUserId,
    required this.remark,
    required this.createTime,
    required this.addSource,
    required this.operatorUserId,
    required this.nickname,
    required this.faceUrl,
    required this.ex,
    required this.attachedInfo,
    required this.isPinned,
  });

  @override
  int get hashCode =>
      ownerUserId.hashCode ^
      friendUserId.hashCode ^
      remark.hashCode ^
      createTime.hashCode ^
      addSource.hashCode ^
      operatorUserId.hashCode ^
      nickname.hashCode ^
      faceUrl.hashCode ^
      ex.hashCode ^
      attachedInfo.hashCode ^
      isPinned.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalFriend &&
          runtimeType == other.runtimeType &&
          ownerUserId == other.ownerUserId &&
          friendUserId == other.friendUserId &&
          remark == other.remark &&
          createTime == other.createTime &&
          addSource == other.addSource &&
          operatorUserId == other.operatorUserId &&
          nickname == other.nickname &&
          faceUrl == other.faceUrl &&
          ex == other.ex &&
          attachedInfo == other.attachedInfo &&
          isPinned == other.isPinned;
}
