// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 本地会话数据结构
/// 可以直接从服务器返回的 JSON 反序列化，缺失的字段使用默认值
class LocalConversation {
  /// 会话 ID
  final String conversationId;

  /// 会话类型：1=单聊, 2=普通群聊, 3=超级群聊, 4=通知会话
  final int conversationType;

  /// 用户 ID（单聊时使用）
  final String userId;

  /// 群组 ID（群聊时使用）
  final String groupId;

  /// 显示名称（服务器不返回，需要从用户/群组信息获取）
  final String showName;

  /// 头像 URL（服务器不返回，需要从用户/群组信息获取）
  final String faceUrl;

  /// 最新消息（服务器不返回，需要从消息获取）
  final String latestMsg;

  /// 最新消息发送时间（服务器不返回，需要从消息获取）
  final PlatformInt64 latestMsgSendTime;

  /// 未读消息数（服务器可能不返回）
  final int unreadCount;

  /// 接收消息选项：0=接收并通知, 1=接收但不通知, 2=屏蔽
  final int recvMsgOpt;

  /// 是否置顶
  final bool isPinned;

  /// 是否私聊
  final bool isPrivateChat;

  /// 阅后即焚时长（秒）
  final int burnDuration;

  /// 群@类型：0=正常, 1=@我, 2=@所有人
  final int groupAtType;

  /// 是否不在群中
  final bool isNotInGroup;

  /// 更新未读数时间
  final PlatformInt64 updateUnreadCountTime;

  /// 附加信息
  final String attachedInfo;

  /// 扩展信息
  final String ex;

  /// 草稿文本
  final String draftText;

  /// 草稿文本时间
  final PlatformInt64 draftTextTime;

  /// 最大序列号
  final PlatformInt64 maxSeq;

  /// 最小序列号
  final PlatformInt64 minSeq;

  /// 是否消息销毁
  final bool isMsgDestruct;

  /// 消息销毁时间
  final PlatformInt64 msgDestructTime;

  const LocalConversation({
    required this.conversationId,
    required this.conversationType,
    required this.userId,
    required this.groupId,
    required this.showName,
    required this.faceUrl,
    required this.latestMsg,
    required this.latestMsgSendTime,
    required this.unreadCount,
    required this.recvMsgOpt,
    required this.isPinned,
    required this.isPrivateChat,
    required this.burnDuration,
    required this.groupAtType,
    required this.isNotInGroup,
    required this.updateUnreadCountTime,
    required this.attachedInfo,
    required this.ex,
    required this.draftText,
    required this.draftTextTime,
    required this.maxSeq,
    required this.minSeq,
    required this.isMsgDestruct,
    required this.msgDestructTime,
  });

  @override
  int get hashCode =>
      conversationId.hashCode ^
      conversationType.hashCode ^
      userId.hashCode ^
      groupId.hashCode ^
      showName.hashCode ^
      faceUrl.hashCode ^
      latestMsg.hashCode ^
      latestMsgSendTime.hashCode ^
      unreadCount.hashCode ^
      recvMsgOpt.hashCode ^
      isPinned.hashCode ^
      isPrivateChat.hashCode ^
      burnDuration.hashCode ^
      groupAtType.hashCode ^
      isNotInGroup.hashCode ^
      updateUnreadCountTime.hashCode ^
      attachedInfo.hashCode ^
      ex.hashCode ^
      draftText.hashCode ^
      draftTextTime.hashCode ^
      maxSeq.hashCode ^
      minSeq.hashCode ^
      isMsgDestruct.hashCode ^
      msgDestructTime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalConversation &&
          runtimeType == other.runtimeType &&
          conversationId == other.conversationId &&
          conversationType == other.conversationType &&
          userId == other.userId &&
          groupId == other.groupId &&
          showName == other.showName &&
          faceUrl == other.faceUrl &&
          latestMsg == other.latestMsg &&
          latestMsgSendTime == other.latestMsgSendTime &&
          unreadCount == other.unreadCount &&
          recvMsgOpt == other.recvMsgOpt &&
          isPinned == other.isPinned &&
          isPrivateChat == other.isPrivateChat &&
          burnDuration == other.burnDuration &&
          groupAtType == other.groupAtType &&
          isNotInGroup == other.isNotInGroup &&
          updateUnreadCountTime == other.updateUnreadCountTime &&
          attachedInfo == other.attachedInfo &&
          ex == other.ex &&
          draftText == other.draftText &&
          draftTextTime == other.draftTextTime &&
          maxSeq == other.maxSeq &&
          minSeq == other.minSeq &&
          isMsgDestruct == other.isMsgDestruct &&
          msgDestructTime == other.msgDestructTime;
}
