// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            

            

            /// @ 元素
class AtElem  {
                final String text;
final List<String> atUserList;
final List<AtInfo>? atUsersInfo;
final MsgStruct? quoteMessage;
final bool isAtSelf;

                const AtElem({required this.text ,required this.atUserList ,this.atUsersInfo ,this.quoteMessage ,required this.isAtSelf ,});

                
                

                
        @override
        int get hashCode => text.hashCode^atUserList.hashCode^atUsersInfo.hashCode^quoteMessage.hashCode^isAtSelf.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is AtElem &&
                runtimeType == other.runtimeType
                && text == other.text&& atUserList == other.atUserList&& atUsersInfo == other.atUsersInfo&& quoteMessage == other.quoteMessage&& isAtSelf == other.isAtSelf;
        
            }

/// @ 用户信息
class AtInfo  {
                final String? atUserId;
final String? groupNickname;

                const AtInfo({this.atUserId ,this.groupNickname ,});

                
                

                
        @override
        int get hashCode => atUserId.hashCode^groupNickname.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is AtInfo &&
                runtimeType == other.runtimeType
                && atUserId == other.atUserId&& groupNickname == other.groupNickname;
        
            }

/// 自定义元素
class CustomElem  {
                final String data;
final String description;
final String extension_;

                const CustomElem({required this.data ,required this.description ,required this.extension_ ,});

                
                

                
        @override
        int get hashCode => data.hashCode^description.hashCode^extension_.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is CustomElem &&
                runtimeType == other.runtimeType
                && data == other.data&& description == other.description&& extension_ == other.extension_;
        
            }

/// 文件元素
class FileElem  {
                final String filePath;
final String uuid;
final String sourceUrl;
final String fileName;
final PlatformInt64 fileSize;

                const FileElem({required this.filePath ,required this.uuid ,required this.sourceUrl ,required this.fileName ,required this.fileSize ,});

                
                

                
        @override
        int get hashCode => filePath.hashCode^uuid.hashCode^sourceUrl.hashCode^fileName.hashCode^fileSize.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is FileElem &&
                runtimeType == other.runtimeType
                && filePath == other.filePath&& uuid == other.uuid&& sourceUrl == other.sourceUrl&& fileName == other.fileName&& fileSize == other.fileSize;
        
            }

/// 获取高级历史消息列表回调（完全匹配 Go SDK 的 GetAdvancedHistoryMessageListCallback）
class GetAdvancedHistoryMessageListCallback  {
                final List<MsgStruct> messageList;
final bool isEnd;
final int errCode;
final String errMsg;

                const GetAdvancedHistoryMessageListCallback({required this.messageList ,required this.isEnd ,required this.errCode ,required this.errMsg ,});

                
                

                
        @override
        int get hashCode => messageList.hashCode^isEnd.hashCode^errCode.hashCode^errMsg.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is GetAdvancedHistoryMessageListCallback &&
                runtimeType == other.runtimeType
                && messageList == other.messageList&& isEnd == other.isEnd&& errCode == other.errCode&& errMsg == other.errMsg;
        
            }

/// 获取高级历史消息列表参数（完全匹配 Go SDK 的 GetAdvancedHistoryMessageListParams）
class GetAdvancedHistoryMessageListParams  {
                final String conversationId;
final String startClientMsgId;
final int count;
final int viewType;

                const GetAdvancedHistoryMessageListParams({required this.conversationId ,required this.startClientMsgId ,required this.count ,required this.viewType ,});

                
                

                
        @override
        int get hashCode => conversationId.hashCode^startClientMsgId.hashCode^count.hashCode^viewType.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is GetAdvancedHistoryMessageListParams &&
                runtimeType == other.runtimeType
                && conversationId == other.conversationId&& startClientMsgId == other.startClientMsgId&& count == other.count&& viewType == other.viewType;
        
            }

/// 位置元素
class LocationElem  {
                final String description;
final double longitude;
final double latitude;

                const LocationElem({required this.description ,required this.longitude ,required this.latitude ,});

                
                

                
        @override
        int get hashCode => description.hashCode^longitude.hashCode^latitude.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is LocationElem &&
                runtimeType == other.runtimeType
                && description == other.description&& longitude == other.longitude&& latitude == other.latitude;
        
            }

/// 消息撤回信息
class MessageRevoked  {
                final String revokerId;
final int revokerRole;
final String clientMsgId;
final String revokerNickname;
final int sessionType;
final int seq;

                const MessageRevoked({required this.revokerId ,required this.revokerRole ,required this.clientMsgId ,required this.revokerNickname ,required this.sessionType ,required this.seq ,});

                
                

                
        @override
        int get hashCode => revokerId.hashCode^revokerRole.hashCode^clientMsgId.hashCode^revokerNickname.hashCode^sessionType.hashCode^seq.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is MessageRevoked &&
                runtimeType == other.runtimeType
                && revokerId == other.revokerId&& revokerRole == other.revokerRole&& clientMsgId == other.clientMsgId&& revokerNickname == other.revokerNickname&& sessionType == other.sessionType&& seq == other.seq;
        
            }

/// 消息结构体（对应 Go 的 MsgStruct）
class MsgStruct  {
                final String? clientMsgId;
final String? serverMsgId;
final PlatformInt64 createTime;
final PlatformInt64 sendTime;
final int sessionType;
final String? sendId;
final String? recvId;
final int msgFrom;
final int contentType;
final int senderPlatformId;
final String? senderNickname;
final String? senderFaceUrl;
final String? groupId;
final String? content;
final PlatformInt64 seq;
final bool isRead;
final int status;
final bool? isReact;
final bool? isExternalExtensions;
final OfflinePushInfo? offlinePush;
final String? attachedInfo;
final String? ex;
final String? localEx;
final TextElem? textElem;
final PictureElem? pictureElem;
final SoundElem? soundElem;
final VideoElem? videoElem;
final FileElem? fileElem;
final AtElem? atTextElem;
final LocationElem? locationElem;
final CustomElem? customElem;
final QuoteElem? quoteElem;

                const MsgStruct({this.clientMsgId ,this.serverMsgId ,required this.createTime ,required this.sendTime ,required this.sessionType ,this.sendId ,this.recvId ,required this.msgFrom ,required this.contentType ,required this.senderPlatformId ,this.senderNickname ,this.senderFaceUrl ,this.groupId ,this.content ,required this.seq ,required this.isRead ,required this.status ,this.isReact ,this.isExternalExtensions ,this.offlinePush ,this.attachedInfo ,this.ex ,this.localEx ,this.textElem ,this.pictureElem ,this.soundElem ,this.videoElem ,this.fileElem ,this.atTextElem ,this.locationElem ,this.customElem ,this.quoteElem ,});

                
                

                
        @override
        int get hashCode => clientMsgId.hashCode^serverMsgId.hashCode^createTime.hashCode^sendTime.hashCode^sessionType.hashCode^sendId.hashCode^recvId.hashCode^msgFrom.hashCode^contentType.hashCode^senderPlatformId.hashCode^senderNickname.hashCode^senderFaceUrl.hashCode^groupId.hashCode^content.hashCode^seq.hashCode^isRead.hashCode^status.hashCode^isReact.hashCode^isExternalExtensions.hashCode^offlinePush.hashCode^attachedInfo.hashCode^ex.hashCode^localEx.hashCode^textElem.hashCode^pictureElem.hashCode^soundElem.hashCode^videoElem.hashCode^fileElem.hashCode^atTextElem.hashCode^locationElem.hashCode^customElem.hashCode^quoteElem.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is MsgStruct &&
                runtimeType == other.runtimeType
                && clientMsgId == other.clientMsgId&& serverMsgId == other.serverMsgId&& createTime == other.createTime&& sendTime == other.sendTime&& sessionType == other.sessionType&& sendId == other.sendId&& recvId == other.recvId&& msgFrom == other.msgFrom&& contentType == other.contentType&& senderPlatformId == other.senderPlatformId&& senderNickname == other.senderNickname&& senderFaceUrl == other.senderFaceUrl&& groupId == other.groupId&& content == other.content&& seq == other.seq&& isRead == other.isRead&& status == other.status&& isReact == other.isReact&& isExternalExtensions == other.isExternalExtensions&& offlinePush == other.offlinePush&& attachedInfo == other.attachedInfo&& ex == other.ex&& localEx == other.localEx&& textElem == other.textElem&& pictureElem == other.pictureElem&& soundElem == other.soundElem&& videoElem == other.videoElem&& fileElem == other.fileElem&& atTextElem == other.atTextElem&& locationElem == other.locationElem&& customElem == other.customElem&& quoteElem == other.quoteElem;
        
            }

/// 图片基础信息
class PictureBaseInfo  {
                final String uuid;
final String type;
final PlatformInt64 size;
final int width;
final int height;
final String url;

                const PictureBaseInfo({required this.uuid ,required this.type ,required this.size ,required this.width ,required this.height ,required this.url ,});

                
                

                
        @override
        int get hashCode => uuid.hashCode^type.hashCode^size.hashCode^width.hashCode^height.hashCode^url.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is PictureBaseInfo &&
                runtimeType == other.runtimeType
                && uuid == other.uuid&& type == other.type&& size == other.size&& width == other.width&& height == other.height&& url == other.url;
        
            }

/// 图片元素
class PictureElem  {
                final String sourcePath;
final PictureBaseInfo sourcePicture;
final PictureBaseInfo bigPicture;
final PictureBaseInfo snapshotPicture;

                const PictureElem({required this.sourcePath ,required this.sourcePicture ,required this.bigPicture ,required this.snapshotPicture ,});

                
                

                
        @override
        int get hashCode => sourcePath.hashCode^sourcePicture.hashCode^bigPicture.hashCode^snapshotPicture.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is PictureElem &&
                runtimeType == other.runtimeType
                && sourcePath == other.sourcePath&& sourcePicture == other.sourcePicture&& bigPicture == other.bigPicture&& snapshotPicture == other.snapshotPicture;
        
            }

/// 引用元素
class QuoteElem  {
                final String? text;
final MsgStruct? quoteMessage;

                const QuoteElem({this.text ,this.quoteMessage ,});

                
                

                
        @override
        int get hashCode => text.hashCode^quoteMessage.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is QuoteElem &&
                runtimeType == other.runtimeType
                && text == other.text&& quoteMessage == other.quoteMessage;
        
            }

/// 语音元素
class SoundElem  {
                final String uuid;
final String soundPath;
final String sourceUrl;
final PlatformInt64 dataSize;
final PlatformInt64 duration;

                const SoundElem({required this.uuid ,required this.soundPath ,required this.sourceUrl ,required this.dataSize ,required this.duration ,});

                
                

                
        @override
        int get hashCode => uuid.hashCode^soundPath.hashCode^sourceUrl.hashCode^dataSize.hashCode^duration.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is SoundElem &&
                runtimeType == other.runtimeType
                && uuid == other.uuid&& soundPath == other.soundPath&& sourceUrl == other.sourceUrl&& dataSize == other.dataSize&& duration == other.duration;
        
            }

/// 文本元素
class TextElem  {
                final String content;

                const TextElem({required this.content ,});

                
                

                
        @override
        int get hashCode => content.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is TextElem &&
                runtimeType == other.runtimeType
                && content == other.content;
        
            }

/// 输入提示（typing）状态信息
class TypingStatus  {
                final String conversationId;
final String? sendId;
final String msgTip;

                const TypingStatus({required this.conversationId ,this.sendId ,required this.msgTip ,});

                
                

                
        @override
        int get hashCode => conversationId.hashCode^sendId.hashCode^msgTip.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is TypingStatus &&
                runtimeType == other.runtimeType
                && conversationId == other.conversationId&& sendId == other.sendId&& msgTip == other.msgTip;
        
            }

/// 视频元素
class VideoElem  {
                final String videoPath;
final String videoUuid;
final String videoUrl;
final String videoType;
final PlatformInt64 videoSize;
final PlatformInt64 duration;
final String snapshotPath;
final String snapshotUuid;
final PlatformInt64 snapshotSize;
final String snapshotUrl;
final int snapshotWidth;
final int snapshotHeight;

                const VideoElem({required this.videoPath ,required this.videoUuid ,required this.videoUrl ,required this.videoType ,required this.videoSize ,required this.duration ,required this.snapshotPath ,required this.snapshotUuid ,required this.snapshotSize ,required this.snapshotUrl ,required this.snapshotWidth ,required this.snapshotHeight ,});

                
                

                
        @override
        int get hashCode => videoPath.hashCode^videoUuid.hashCode^videoUrl.hashCode^videoType.hashCode^videoSize.hashCode^duration.hashCode^snapshotPath.hashCode^snapshotUuid.hashCode^snapshotSize.hashCode^snapshotUrl.hashCode^snapshotWidth.hashCode^snapshotHeight.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is VideoElem &&
                runtimeType == other.runtimeType
                && videoPath == other.videoPath&& videoUuid == other.videoUuid&& videoUrl == other.videoUrl&& videoType == other.videoType&& videoSize == other.videoSize&& duration == other.duration&& snapshotPath == other.snapshotPath&& snapshotUuid == other.snapshotUuid&& snapshotSize == other.snapshotSize&& snapshotUrl == other.snapshotUrl&& snapshotWidth == other.snapshotWidth&& snapshotHeight == other.snapshotHeight;
        
            }
            