// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../im/auth.dart';
import '../im/types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<OpenIMBridgeClient>>
abstract class OpenImBridgeClient implements RustOpaqueInterface {
  /// 连接到服务器
  ///
  /// 建立 WebSocket 连接并启动消息监听。
  /// 连接成功后会自动启动心跳和消息处理任务。
  Future<void> connect();

  static Future<LoginResponse> loginAsync({
    required String areaCode,
    required String phoneNumber,
    required String password,
    required int platform,
  }) => RustLib.instance.api.crateApiBridgeClientOpenImBridgeClientLoginAsync(
    areaCode: areaCode,
    phoneNumber: phoneNumber,
    password: password,
    platform: platform,
  );

  /// 创建新的客户端实例
  ///
  /// # 参数
  /// - `user_id`: 用户 ID
  /// - `token`: 认证 token（从登录接口获取）
  /// - `platform_id`: 平台 ID（例如：5 表示 Web）
  /// - `ws_url`: WebSocket 服务器 URL（可选，默认使用 localhost:10001）
  ///
  /// # 返回
  /// 返回客户端实例
  factory OpenImBridgeClient({
    required String userId,
    required String token,
    required int platformId,
    String? wsUrl,
  }) => RustLib.instance.api.crateApiBridgeClientOpenImBridgeClientNew(
    userId: userId,
    token: token,
    platformId: platformId,
    wsUrl: wsUrl,
  );

  /// 发送文本消息
  ///
  /// # 参数
  /// - `recv_id`: 接收者 ID
  /// - `text`: 消息文本内容
  /// - `session_type`: 会话类型（1=单聊, 2=群聊）
  Future<void> sendTextMessage({
    required String recvId,
    required String text,
    required int sessionType,
  });

  /// 订阅消息事件
  ///
  /// 订阅客户端内部的消息事件流。
  /// 在 Dart 端会返回一个 Stream<MessageEvent>，持续接收事件直到连接断开。
  ///
  /// # 事件类型
  /// - `NewMessage`: 收到新消息，包含完整的 MessageData
  /// - `SendMessageResponse`: 消息发送响应
  /// - `KickedOffline`: 被踢下线
  /// - `ConnectionStatus`: 连接状态变化
  /// - `Other`: 其他消息
  ///
  /// # Dart 使用示例
  /// ```dart
  /// final stream = client.subscribeMessages();
  /// stream.listen((event) {
  ///   if (event is NewMessage) {
  ///     print('收到消息: ${event.message.sendId} -> ${event.message.recvId}');
  ///   }
  /// });
  /// ```
  Stream<MessageEvent> subscribeMessages();
}
