// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they have generic arguments: `on_black_list_changed`, `on_conversation_changed`, `on_conversation_user_input_status_changed`, `on_friend_list_changed`, `on_friend_request_list_changed`, `on_new_conversation`, `on_sync_server_failed`, `on_sync_server_finish`, `on_sync_server_progress`, `on_sync_server_start`, `on_total_unread_message_count_changed`

/// 桥接到 Dart 的会话监听器实现
class BridgeConversationListener {
  /// Dart 侧的会话事件流（JSON 字符串）
  final RustStreamSink<String>? convSink;

  /// Dart 侧的总未读数事件流（整型）
  final RustStreamSink<int>? unreadSink;

  const BridgeConversationListener({this.convSink, this.unreadSink});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<BridgeConversationListener> newInstance({
    RustStreamSink<String>? convSink,
    RustStreamSink<int>? unreadSink,
  }) => RustLib.instance.api.crateApiListenersBridgeConversationListenerNew(
    convSink: convSink,
    unreadSink: unreadSink,
  );

  @override
  int get hashCode => convSink.hashCode ^ unreadSink.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeConversationListener &&
          runtimeType == other.runtimeType &&
          convSink == other.convSink &&
          unreadSink == other.unreadSink;
}

/// 桥接到 Dart 的好友监听器实现
class BridgeFriendListener {
  /// 好友列表变更事件流（JSON 数组）
  final RustStreamSink<String>? friendSink;

  /// 黑名单变更事件流（JSON 数组）
  final RustStreamSink<String>? blackSink;

  /// 好友申请变更事件流（JSON 数组）
  final RustStreamSink<String>? requestSink;

  const BridgeFriendListener({
    this.friendSink,
    this.blackSink,
    this.requestSink,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<BridgeFriendListener> newInstance({
    RustStreamSink<String>? friendSink,
    RustStreamSink<String>? blackSink,
    RustStreamSink<String>? requestSink,
  }) => RustLib.instance.api.crateApiListenersBridgeFriendListenerNew(
    friendSink: friendSink,
    blackSink: blackSink,
    requestSink: requestSink,
  );

  @override
  int get hashCode =>
      friendSink.hashCode ^ blackSink.hashCode ^ requestSink.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeFriendListener &&
          runtimeType == other.runtimeType &&
          friendSink == other.friendSink &&
          blackSink == other.blackSink &&
          requestSink == other.requestSink;
}
