// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../domain/constant.dart';
import '../domain/model/msg_struct.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> uploadFile({
  required String filePath,
  required String fileName,
}) => RustLib.instance.api.crateApiMessageMediaUploadFile(
  filePath: filePath,
  fileName: fileName,
);

Stream<int> uploadFileWithProgress({
  required String filePath,
  required String fileName,
}) => RustLib.instance.api.crateApiMessageMediaUploadFileWithProgress(
  filePath: filePath,
  fileName: fileName,
);

/// 从 URL 发送图片消息
Future<MsgStruct> sendImageMessageFromUrl({
  required String sourceUrl,
  required String sourceId,
  required SessionType sessionType,
}) => RustLib.instance.api.crateApiMessageMediaSendImageMessageFromUrl(
  sourceUrl: sourceUrl,
  sourceId: sourceId,
  sessionType: sessionType,
);

/// 从 URL 发送语音消息
Future<MsgStruct> sendSoundMessageFromUrl({
  required String sourceUrl,
  required PlatformInt64 duration,
  required String sourceId,
  required SessionType sessionType,
}) => RustLib.instance.api.crateApiMessageMediaSendSoundMessageFromUrl(
  sourceUrl: sourceUrl,
  duration: duration,
  sourceId: sourceId,
  sessionType: sessionType,
);

/// 从 URL 发送视频消息
Future<MsgStruct> sendVideoMessageFromUrl({
  required String sourceUrl,
  required PlatformInt64 duration,
  required String snapshotUrl,
  required String sourceId,
  required SessionType sessionType,
}) => RustLib.instance.api.crateApiMessageMediaSendVideoMessageFromUrl(
  sourceUrl: sourceUrl,
  duration: duration,
  snapshotUrl: snapshotUrl,
  sourceId: sourceId,
  sessionType: sessionType,
);

/// 从 URL 发送文件消息
Future<MsgStruct> sendFileMessageFromUrl({
  required String sourceUrl,
  required String fileName,
  required PlatformInt64 fileSize,
  required String sourceId,
  required SessionType sessionType,
}) => RustLib.instance.api.crateApiMessageMediaSendFileMessageFromUrl(
  sourceUrl: sourceUrl,
  fileName: fileName,
  fileSize: fileSize,
  sourceId: sourceId,
  sessionType: sessionType,
);
