// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

/// 初始化 Rust 日志，供 Dart 异步设置日志级别
Future<void> initLogger({required String logLevel}) =>
    RustLib.instance.api.crateApiSimpleInitLogger(logLevel: logLevel);
