// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 测试上传文件（使用本地路径，不经过完整的上传流程）
/// 仅用于测试文件上传是否正常工作
Future<String> testUploadFile({
  required String filePath,
  required String fileName,
}) => RustLib.instance.api.crateApiTestUploadTestUploadFile(
  filePath: filePath,
  fileName: fileName,
);
