// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `send_event`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < Mutex < Option < StreamSink < ConnectionStatusEvent > > > >>>
abstract class ArcMutexOptionStreamSinkConnectionStatusEvent
    implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DartConnectionStatusListener>>
abstract class DartConnectionStatusListener implements RustOpaqueInterface {
  ArcMutexOptionStreamSinkConnectionStatusEvent get sink;

  set sink(ArcMutexOptionStreamSinkConnectionStatusEvent sink);

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<DartConnectionStatusListener> newInstance() => RustLib
      .instance
      .api
      .crateApiListenersConnectionStatusDartConnectionStatusListenerNew();

  /// 设置连接状态 sink
  Stream<ConnectionStatusEvent> setSink();
}

/// 连接状态事件
class ConnectionStatusEvent {
  final bool connected;
  final String message;

  const ConnectionStatusEvent({required this.connected, required this.message});

  @override
  int get hashCode => connected.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConnectionStatusEvent &&
          runtimeType == other.runtimeType &&
          connected == other.connected &&
          message == other.message;
}
