// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../im/model/message.dart';
import '../../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'message.freezed.dart';

            // These functions are ignored because they are not marked as `pub`: `send_event`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`


            

            
                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < Mutex < Option < StreamSink < MessageEvent > > > >>>
                abstract class ArcMutexOptionStreamSinkMessageEvent implements RustOpaqueInterface {
                    

                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DartMessageListener>>
                abstract class DartMessageListener implements RustOpaqueInterface {
                     ArcMutexOptionStreamSinkMessageEvent get sink;


  set sink(ArcMutexOptionStreamSinkMessageEvent sink);


  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
static Future<DartMessageListener>  newInstance()=>RustLib.instance.api.crateApiListenersMessageDartMessageListenerNew();


/// 设置消息 sink
 Stream<MessageEvent>  setSink();



                    
                }
                

@freezed
                sealed class MessageEvent with _$MessageEvent  {
                    const MessageEvent._();

                     /// 收到新消息（在线消息）
const factory MessageEvent.recvNewMessage({   required MsgStruct message , }) = MessageEvent_RecvNewMessage;
 /// 收到 C2C 已读回执
/// 参数 `msg_receipt_list` 是已读回执列表的 JSON 字符串表示（列表结构较复杂，暂用 String）
const factory MessageEvent.recvC2CReadReceipt({   required String msgReceiptList , }) = MessageEvent_RecvC2CReadReceipt;
 /// 收到消息撤回通知
const factory MessageEvent.newRecvMessageRevoked({   required MessageRevoked messageRevoked , }) = MessageEvent_NewRecvMessageRevoked;
 /// 收到离线新消息
const factory MessageEvent.recvOfflineNewMessage({   required MsgStruct message , }) = MessageEvent_RecvOfflineNewMessage;
 /// 消息被删除
/// 参数 `message` 是删除消息信息的 JSON 字符串表示（可能是 MsgStruct 或删除信息）
const factory MessageEvent.msgDeleted({   required MsgStruct message , }) = MessageEvent_MsgDeleted;
 /// 收到仅在线消息（不存储到本地）
const factory MessageEvent.recvOnlineOnlyMessage({   required MsgStruct message , }) = MessageEvent_RecvOnlineOnlyMessage;
 /// 被踢下线
const factory MessageEvent.kickedOffline() = MessageEvent_KickedOffline;
 /// 收到输入提示（typing）状态
const factory MessageEvent.recvTypingStatus({   required TypingStatus typingStatus , }) = MessageEvent_RecvTypingStatus;

                    

                    
                }
            