// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 群聊已读回执（对齐 Go SDK OnRecvGroupReadReceipt）
class GroupReadReceipt {
  final String groupId;
  final String msgId;
  final List<String> hasReadUserIdList;
  final int hasReadCount;
  final int groupMemberCount;
  final PlatformInt64 readTime;

  const GroupReadReceipt({
    required this.groupId,
    required this.msgId,
    required this.hasReadUserIdList,
    required this.hasReadCount,
    required this.groupMemberCount,
    required this.readTime,
  });

  @override
  int get hashCode =>
      groupId.hashCode ^
      msgId.hashCode ^
      hasReadUserIdList.hashCode ^
      hasReadCount.hashCode ^
      groupMemberCount.hashCode ^
      readTime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupReadReceipt &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId &&
          msgId == other.msgId &&
          hasReadUserIdList == other.hasReadUserIdList &&
          hasReadCount == other.hasReadCount &&
          groupMemberCount == other.groupMemberCount &&
          readTime == other.readTime;
}
