// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../domain/model/friend.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'friend.freezed.dart';

@freezed
sealed class FriendEvent with _$FriendEvent {
  const FriendEvent._();

  const factory FriendEvent.added(List<FriendInfo> field0) = FriendEvent_Added;
  const factory FriendEvent.deleted(String field0) = FriendEvent_Deleted;
  const factory FriendEvent.infoChanged(List<FriendInfo> field0) =
      FriendEvent_InfoChanged;
  const factory FriendEvent.blackAdded(String field0) = FriendEvent_BlackAdded;
  const factory FriendEvent.blackDeleted(String field0) =
      FriendEvent_BlackDeleted;
  const factory FriendEvent.applicationAdded(String field0) =
      FriendEvent_ApplicationAdded;
  const factory FriendEvent.applicationAccepted(String field0) =
      FriendEvent_ApplicationAccepted;
  const factory FriendEvent.applicationRejected(String field0) =
      FriendEvent_ApplicationRejected;
}
