// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../lib.dart';
import '../model/conversation.dart';
import '../model/friend.dart';
import '../model/message.dart';
import '../model/user.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'types.freezed.dart';

/// 群聊已读回执（对齐 Go SDK `OnRecvGroupReadReceipt`）
class GroupReadReceipt {
  final String groupId;
  final String msgId;
  final List<String> hasReadUserIdList;
  final int hasReadCount;
  final int groupMemberCount;
  final PlatformInt64 readTime;

  const GroupReadReceipt({
    required this.groupId,
    required this.msgId,
    required this.hasReadUserIdList,
    required this.hasReadCount,
    required this.groupMemberCount,
    required this.readTime,
  });

  @override
  int get hashCode =>
      groupId.hashCode ^
      msgId.hashCode ^
      hasReadUserIdList.hashCode ^
      hasReadCount.hashCode ^
      groupMemberCount.hashCode ^
      readTime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupReadReceipt &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId &&
          msgId == other.msgId &&
          hasReadUserIdList == other.hasReadUserIdList &&
          hasReadCount == other.hasReadCount &&
          groupMemberCount == other.groupMemberCount &&
          readTime == other.readTime;
}

/// 用户输入状态变化数据（对齐 Go SDK `OnConversationUserInputStatusChanged`）
class InputStatusChangedData {
  final String conversationId;
  final String userId;
  final Int32List platformIds;

  const InputStatusChangedData({
    required this.conversationId,
    required this.userId,
    required this.platformIds,
  });

  @override
  int get hashCode =>
      conversationId.hashCode ^ userId.hashCode ^ platformIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InputStatusChangedData &&
          runtimeType == other.runtimeType &&
          conversationId == other.conversationId &&
          userId == other.userId &&
          platformIds == other.platformIds;
}

/// 消息扩展（Reaction）变更数据（对齐 Go SDK `OnRecvMessageExtensionsChanged` 等）
class MessageExtensionData {
  final String clientMsgId;
  final String reactionExtensionList;

  const MessageExtensionData({
    required this.clientMsgId,
    required this.reactionExtensionList,
  });

  @override
  int get hashCode => clientMsgId.hashCode ^ reactionExtensionList.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageExtensionData &&
          runtimeType == other.runtimeType &&
          clientMsgId == other.clientMsgId &&
          reactionExtensionList == other.reactionExtensionList;
}

/// C2C 已读回执（对齐 Go SDK `sdkws.MessageReceipt`）
class MessageReceipt {
  final String userId;
  final List<String> msgIds;
  final PlatformInt64 readTime;
  final int sessionType;

  const MessageReceipt({
    required this.userId,
    required this.msgIds,
    required this.readTime,
    required this.sessionType,
  });

  @override
  int get hashCode =>
      userId.hashCode ^
      msgIds.hashCode ^
      readTime.hashCode ^
      sessionType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageReceipt &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          msgIds == other.msgIds &&
          readTime == other.readTime &&
          sessionType == other.sessionType;
}

@freezed
sealed class SdkEvent with _$SdkEvent {
  const SdkEvent._();

  const factory SdkEvent.connecting() = SdkEvent_Connecting;
  const factory SdkEvent.connected() = SdkEvent_Connected;
  const factory SdkEvent.disconnected({required String reason}) =
      SdkEvent_Disconnected;
  const factory SdkEvent.connectFailed({required String error}) =
      SdkEvent_ConnectFailed;
  const factory SdkEvent.pushMessage({
    required int reqIdentifier,
    required Uint8List data,
  }) = SdkEvent_PushMessage;
  const factory SdkEvent.pushMessages({
    required String conversationId,
    required List<MsgData> msgs,
    required bool isEnd,
    required PlatformInt64 endSeq,
  }) = SdkEvent_PushMessages;
  const factory SdkEvent.pushNotificationMessages({
    required String conversationId,
    required List<MsgData> msgs,
    required bool isEnd,
    required PlatformInt64 endSeq,
  }) = SdkEvent_PushNotificationMessages;
  const factory SdkEvent.syncStarted() = SdkEvent_SyncStarted;
  const factory SdkEvent.syncProgress({
    required int progress,
    required String message,
  }) = SdkEvent_SyncProgress;
  const factory SdkEvent.syncFinished() = SdkEvent_SyncFinished;
  const factory SdkEvent.syncFailed({required String error}) =
      SdkEvent_SyncFailed;
  const factory SdkEvent.newMessage({required ReceivedMessage message}) =
      SdkEvent_NewMessage;
  const factory SdkEvent.messageSent({
    required String clientMsgId,
    required String serverMsgId,
    required PlatformInt64 sendTime,
    required int status,
    required String conversationId,
    required String sendId,
    required String recvId,
    required String groupId,
    required int sessionType,
    required int contentType,
    required String content,
    required String senderNickname,
    required String senderFaceUrl,
  }) = SdkEvent_MessageSent;
  const factory SdkEvent.messageSendFailed({
    required String clientMsgId,
    required String error,
  }) = SdkEvent_MessageSendFailed;
  const factory SdkEvent.uploadProgress({
    required String clientMsgId,
    required int progress,
    required BigInt totalSize,
    required BigInt uploadedSize,
  }) = SdkEvent_UploadProgress;
  const factory SdkEvent.messageRevoked({
    required String conversationId,
    required PlatformInt64 seq,
    required String clientMsgId,
  }) = SdkEvent_MessageRevoked;

  /// C2C 已读回执（对齐 Go SDK `OnRecvC2CReadReceipt`）
  const factory SdkEvent.c2CReadReceipt({
    required List<MessageReceipt> receipts,
  }) = SdkEvent_C2CReadReceipt;

  /// 群聊已读回执（对齐 Go SDK `OnRecvGroupReadReceipt`）
  const factory SdkEvent.groupReadReceipt({
    required List<GroupReadReceipt> receipts,
  }) = SdkEvent_GroupReadReceipt;

  /// 用户输入状态变化（对齐 Go SDK `OnConversationUserInputStatusChanged`）
  const factory SdkEvent.conversationUserInputStatusChanged({
    required InputStatusChangedData data,
  }) = SdkEvent_ConversationUserInputStatusChanged;

  /// 离线新消息通知（对齐 Go SDK `OnRecvOfflineNewMessage`）
  const factory SdkEvent.recvOfflineNewMessage({
    required List<ReceivedMessage> messages,
  }) = SdkEvent_RecvOfflineNewMessage;

  /// 消息被编辑通知（对齐 Go SDK `OnMsgEdited` / `OnRecvMessageModified`）
  const factory SdkEvent.msgEdited({required ReceivedMessage message}) =
      SdkEvent_MsgEdited;

  /// 消息扩展（Reaction）新增（对齐 Go SDK `OnRecvMessageExtensionsAdded`）
  const factory SdkEvent.messageExtensionsAdded({
    required MessageExtensionData data,
  }) = SdkEvent_MessageExtensionsAdded;

  /// 消息扩展（Reaction）变更（对齐 Go SDK `OnRecvMessageExtensionsChanged`）
  const factory SdkEvent.messageExtensionsChanged({
    required MessageExtensionData data,
  }) = SdkEvent_MessageExtensionsChanged;

  /// 消息扩展（Reaction）删除（对齐 Go SDK `OnRecvMessageExtensionsDeleted`）
  const factory SdkEvent.messageExtensionsDeleted({
    required MessageExtensionData data,
  }) = SdkEvent_MessageExtensionsDeleted;
  const factory SdkEvent.messagesDeleted({
    required String conversationId,
    required List<String> clientMsgIds,
  }) = SdkEvent_MessagesDeleted;
  const factory SdkEvent.conversationChanged({
    required List<Conversation> conversations,
  }) = SdkEvent_ConversationChanged;
  const factory SdkEvent.conversationDeleted({
    required List<String> conversationIds,
  }) = SdkEvent_ConversationDeleted;
  const factory SdkEvent.newConversation({
    required List<Conversation> conversations,
  }) = SdkEvent_NewConversation;
  const factory SdkEvent.totalUnreadCountChanged({
    required PlatformInt64 count,
  }) = SdkEvent_TotalUnreadCountChanged;
  const factory SdkEvent.friendApplicationAdded({required String application}) =
      SdkEvent_FriendApplicationAdded;
  const factory SdkEvent.friendApplicationApproved({
    required String application,
  }) = SdkEvent_FriendApplicationApproved;
  const factory SdkEvent.friendApplicationRejected({
    required String application,
  }) = SdkEvent_FriendApplicationRejected;
  const factory SdkEvent.friendAdded({required List<FriendInfo> friends}) =
      SdkEvent_FriendAdded;
  const factory SdkEvent.friendDeleted({required String friendId}) =
      SdkEvent_FriendDeleted;
  const factory SdkEvent.blackAdded({required String userId}) =
      SdkEvent_BlackAdded;
  const factory SdkEvent.blackDeleted({required String blackId}) =
      SdkEvent_BlackDeleted;
  const factory SdkEvent.friendInfoUpdated({required String userId}) =
      SdkEvent_FriendInfoUpdated;
  const factory SdkEvent.groupCreated({required String groupId}) =
      SdkEvent_GroupCreated;
  const factory SdkEvent.groupInfoChanged({required String groupId}) =
      SdkEvent_GroupInfoChanged;
  const factory SdkEvent.groupMemberAdded({
    required String groupId,
    required List<String> memberIds,
  }) = SdkEvent_GroupMemberAdded;
  const factory SdkEvent.groupMemberDeleted({
    required String groupId,
    required List<String> memberIds,
  }) = SdkEvent_GroupMemberDeleted;
  const factory SdkEvent.groupApplicationAdded({required String application}) =
      SdkEvent_GroupApplicationAdded;
  const factory SdkEvent.groupApplicationApproved({
    required String application,
  }) = SdkEvent_GroupApplicationApproved;
  const factory SdkEvent.groupApplicationRejected({
    required String application,
  }) = SdkEvent_GroupApplicationRejected;
  const factory SdkEvent.groupDismissed({required String groupId}) =
      SdkEvent_GroupDismissed;
  const factory SdkEvent.groupMuted({required String groupId}) =
      SdkEvent_GroupMuted;
  const factory SdkEvent.groupCancelMuted({required String groupId}) =
      SdkEvent_GroupCancelMuted;
  const factory SdkEvent.groupMemberMuted({
    required String groupId,
    required String userId,
  }) = SdkEvent_GroupMemberMuted;
  const factory SdkEvent.groupMemberCancelMuted({
    required String groupId,
    required String userId,
  }) = SdkEvent_GroupMemberCancelMuted;
  const factory SdkEvent.groupMemberInfoChanged({
    required String groupId,
    required String userId,
  }) = SdkEvent_GroupMemberInfoChanged;
  const factory SdkEvent.groupOwnerTransferred({
    required String groupId,
    required String newOwnerId,
  }) = SdkEvent_GroupOwnerTransferred;
  const factory SdkEvent.userInfoUpdated({required UserInfo user}) =
      SdkEvent_UserInfoUpdated;
  const factory SdkEvent.userStatusChanged({
    required String userId,
    required int status,
    required Int32List platformIds,
  }) = SdkEvent_UserStatusChanged;

  /// 批量推送消息（经 MessageBatcher 聚合后）
  const factory SdkEvent.batchedPushMessages({
    required Map<String, PullMsgs> msgs,
    required Map<String, PullMsgs> notificationMsgs,
  }) = SdkEvent_BatchedPushMessages;
  const factory SdkEvent.kickedOffline({required String reason}) =
      SdkEvent_KickedOffline;
  const factory SdkEvent.reconnecting({
    required int attempt,
    required int maxAttempts,
  }) = SdkEvent_Reconnecting;
  const factory SdkEvent.tokenExpired() = SdkEvent_TokenExpired;
  const factory SdkEvent.loginSuccess({required String userId}) =
      SdkEvent_LoginSuccess;
  const factory SdkEvent.logout() = SdkEvent_Logout;
  const factory SdkEvent.customEvent({
    required String eventType,
    required String data,
  }) = SdkEvent_CustomEvent;
}
