//! API 路径常量，与 openim-sdk-core pkg/api/api.go 完全一致
//! 参考: https://github.com/openimsdk/openim-sdk-core/blob/main/pkg/api/api.go

// ----- auth -----
/// ParseToken = "/auth/parse_token"
pub const AUTH_PARSE_TOKEN: &str = "/auth/parse_token";

// ----- user -----
/// GetUsersInfo = "/user/get_users_info"
pub const USER_GET_USERS_INFO: &str = "/user/get_users_info";
/// UpdateUserInfo = "/user/update_user_info"
pub const USER_UPDATE_USER_INFO: &str = "/user/update_user_info";
/// UpdateUserInfoEx = "/user/update_user_info_ex"
pub const USER_UPDATE_USER_INFO_EX: &str = "/user/update_user_info_ex";
/// UserRegister = "/user/user_register"
pub const USER_USER_REGISTER: &str = "/user/user_register";
/// UserClientConfig = "/user/get_user_client_config"
pub const USER_GET_USER_CLIENT_CONFIG: &str = "/user/get_user_client_config";

// ----- friend -----
/// GetFriendList = "/friend/get_friend_list"
pub const FRIEND_GET_FRIEND_LIST: &str = "/friend/get_friend_list";
/// GetFullFriendUserIDs = "/friend/get_full_friend_user_ids"
pub const FRIEND_GET_FULL_FRIEND_USER_IDS: &str = "/friend/get_full_friend_user_ids";
/// AddFriend = "/friend/add_friend"
pub const FRIEND_ADD_FRIEND: &str = "/friend/add_friend";
/// DeleteFriend = "/friend/delete_friend"
pub const FRIEND_DELETE_FRIEND: &str = "/friend/delete_friend";
/// GetRecvFriendApplicationList = "/friend/get_friend_apply_list"
pub const FRIEND_GET_FRIEND_APPLY_LIST: &str = "/friend/get_friend_apply_list";
/// GetSelfFriendApplicationList = "/friend/get_self_friend_apply_list"
pub const FRIEND_GET_SELF_FRIEND_APPLY_LIST: &str = "/friend/get_self_friend_apply_list";
/// GetBlackList = "/friend/get_black_list"
pub const FRIEND_GET_BLACK_LIST: &str = "/friend/get_black_list";
/// GetIncrementalFriends = "/friend/get_incremental_friends"
pub const FRIEND_GET_INCREMENTAL_FRIENDS: &str = "/friend/get_incremental_friends";
/// GetSelfUnhandledApplyCount = "/friend/get_self_unhandled_apply_count"
pub const FRIEND_GET_SELF_UNHANDLED_APPLY_COUNT: &str = "/friend/get_self_unhandled_apply_count";
/// ImportFriendList = "/friend/import_friend"
pub const FRIEND_IMPORT_FRIEND: &str = "/friend/import_friend";
/// GetDesignatedFriendsApply = "/friend/get_designated_friend_apply"
pub const FRIEND_GET_DESIGNATED_FRIEND_APPLY: &str = "/friend/get_designated_friend_apply";
/// GetDesignatedFriends = "/friend/get_designated_friends"
pub const FRIEND_GET_DESIGNATED_FRIENDS: &str = "/friend/get_designated_friends";
/// AddFriendResponse = "/friend/add_friend_response"
pub const FRIEND_ADD_FRIEND_RESPONSE: &str = "/friend/add_friend_response";
/// UpdateFriends = "/friend/update_friends"
pub const FRIEND_UPDATE_FRIENDS: &str = "/friend/update_friends";
/// AddBlack = "/friend/add_black"
pub const FRIEND_ADD_BLACK: &str = "/friend/add_black";
/// RemoveBlack = "/friend/remove_black"
pub const FRIEND_REMOVE_BLACK: &str = "/friend/remove_black";

// ----- msg -----
/// ClearConversationMsg = "/msg/clear_conversation_msg"
pub const MSG_CLEAR_CONVERSATION_MSG: &str = "/msg/clear_conversation_msg";
/// ClearAllMsg = "/msg/user_clear_all_msg"
pub const MSG_USER_CLEAR_ALL_MSG: &str = "/msg/user_clear_all_msg";
/// DeleteMsgs = "/msg/delete_msgs"
pub const MSG_DELETE_MSGS: &str = "/msg/delete_msgs";
/// RevokeMsg = "/msg/revoke_msg"
pub const MSG_REVOKE_MSG: &str = "/msg/revoke_msg";
/// MarkMsgsAsRead = "/msg/mark_msgs_as_read"
pub const MSG_MARK_MSGS_AS_READ: &str = "/msg/mark_msgs_as_read";
/// GetConversationsHasReadAndMaxSeq = "/msg/get_conversations_has_read_and_max_seq"
pub const MSG_GET_CONVERSATIONS_HAS_READ_AND_MAX_SEQ: &str = "/msg/get_conversations_has_read_and_max_seq";
/// MarkConversationAsRead = "/msg/mark_conversation_as_read"
pub const MSG_MARK_CONVERSATION_AS_READ: &str = "/msg/mark_conversation_as_read";
/// SetConversationHasReadSeq = "/msg/set_conversation_has_read_seq"
pub const MSG_SET_CONVERSATION_HAS_READ_SEQ: &str = "/msg/set_conversation_has_read_seq";
/// SendMsg = "/msg/send_msg"
pub const MSG_SEND_MSG: &str = "/msg/send_msg";
/// GetServerTime = "/msg/get_server_time"
pub const MSG_GET_SERVER_TIME: &str = "/msg/get_server_time";

// ----- group -----
/// GetGroupsInfo = "/group/get_groups_info"
pub const GROUP_GET_GROUPS_INFO: &str = "/group/get_groups_info";
/// GetIncrementalJoinGroup = "/group/get_incremental_join_groups"
pub const GROUP_GET_INCREMENTAL_JOIN_GROUPS: &str = "/group/get_incremental_join_groups";
/// GetIncrementalGroupMemberBatch = "/group/get_incremental_group_members_batch"
pub const GROUP_GET_INCREMENTAL_GROUP_MEMBERS_BATCH: &str = "/group/get_incremental_group_members_batch";
/// GetJoinedGroupList = "/group/get_joined_group_list"
pub const GROUP_GET_JOINED_GROUP_LIST: &str = "/group/get_joined_group_list";
/// GetGroupMemberList = "/group/get_group_member_list"
pub const GROUP_GET_GROUP_MEMBER_LIST: &str = "/group/get_group_member_list";
/// GetGroupMembersInfo = "/group/get_group_members_info"
pub const GROUP_GET_GROUP_MEMBERS_INFO: &str = "/group/get_group_members_info";

// ----- conversation -----
/// GetConversations = "/conversation/get_conversations"
pub const CONVERSATION_GET_CONVERSATIONS: &str = "/conversation/get_conversations";
/// GetAllConversations = "/conversation/get_all_conversations"
pub const CONVERSATION_GET_ALL_CONVERSATIONS: &str = "/conversation/get_all_conversations";
/// SetConversations = "/conversation/set_conversations"
pub const CONVERSATION_SET_CONVERSATIONS: &str = "/conversation/set_conversations";
/// GetIncrementalConversation = "/conversation/get_incremental_conversations"
pub const CONVERSATION_GET_INCREMENTAL_CONVERSATIONS: &str = "/conversation/get_incremental_conversations";
/// GetFullConversationIDs = "/conversation/get_full_conversation_ids"
pub const CONVERSATION_GET_FULL_CONVERSATION_IDS: &str = "/conversation/get_full_conversation_ids";
/// GetOwnerConversation = "/conversation/get_owner_conversation"
pub const CONVERSATION_GET_OWNER_CONVERSATION: &str = "/conversation/get_owner_conversation";
/// GetConversation = "/conversation/get_conversation"
pub const CONVERSATION_GET_CONVERSATION: &str = "/conversation/get_conversation";
/// GetSortedConversationList = "/conversation/get_sorted_conversation_list"
pub const CONVERSATION_GET_SORTED_CONVERSATION_LIST: &str = "/conversation/get_sorted_conversation_list";
/// GetNotNotifyConversationIDs = "/conversation/get_not_notify_conversation_ids"
pub const CONVERSATION_GET_NOT_NOTIFY_CONVERSATION_IDS: &str = "/conversation/get_not_notify_conversation_ids";
/// GetPinnedConversationIDs = "/conversation/get_pinned_conversation_ids"
pub const CONVERSATION_GET_PINNED_CONVERSATION_IDS: &str = "/conversation/get_pinned_conversation_ids";
/// GetActiveConversation (jssdk) = "/jssdk/get_active_conversations"
pub const JSSDK_GET_ACTIVE_CONVERSATIONS: &str = "/jssdk/get_active_conversations";
/// CreateGroup = "/group/create_group"
pub const GROUP_CREATE_GROUP: &str = "/group/create_group";
/// SetGroupInfoEx = "/group/set_group_info_ex"
pub const GROUP_SET_GROUP_INFO_EX: &str = "/group/set_group_info_ex";
/// JoinGroup = "/group/join_group"
pub const GROUP_JOIN_GROUP: &str = "/group/join_group";
/// QuitGroup = "/group/quit_group"
pub const GROUP_QUIT_GROUP: &str = "/group/quit_group";
/// InviteUserToGroup = "/group/invite_user_to_group"
pub const GROUP_INVITE_USER_TO_GROUP: &str = "/group/invite_user_to_group";
/// KickGroupMember = "/group/kick_group"
pub const GROUP_KICK_GROUP: &str = "/group/kick_group";
/// TransferGroup = "/group/transfer_group"
pub const GROUP_TRANSFER_GROUP: &str = "/group/transfer_group";
/// GetRecvGroupApplicationList = "/group/get_recv_group_applicationList"
pub const GROUP_GET_RECV_GROUP_APPLICATION_LIST: &str = "/group/get_recv_group_applicationList";
/// GetSendGroupApplicationList = "/group/get_user_req_group_applicationList"
pub const GROUP_GET_SEND_GROUP_APPLICATION_LIST: &str = "/group/get_user_req_group_applicationList";
/// GetGroupApplicationUnhandledCount = "/group/get_group_application_unhandled_count"
pub const GROUP_GET_GROUP_APPLICATION_UNHANDLED_COUNT: &str = "/group/get_group_application_unhandled_count";
/// AcceptGroupApplication = "/group/group_application_response"
pub const GROUP_ACCEPT_GROUP_APPLICATION: &str = "/group/group_application_response";
/// DismissGroup = "/group/dismiss_group"
pub const GROUP_DISMISS_GROUP: &str = "/group/dismiss_group";
/// MuteGroupMember = "/group/mute_group_member"
pub const GROUP_MUTE_GROUP_MEMBER: &str = "/group/mute_group_member";
/// CancelMuteGroupMember = "/group/cancel_mute_group_member"
pub const GROUP_CANCEL_MUTE_GROUP_MEMBER: &str = "/group/cancel_mute_group_member";
/// MuteGroup = "/group/mute_group"
pub const GROUP_MUTE_GROUP: &str = "/group/mute_group";
/// CancelMuteGroup = "/group/cancel_mute_group"
pub const GROUP_CANCEL_MUTE_GROUP: &str = "/group/cancel_mute_group";
/// SetGroupMemberInfo = "/group/set_group_member_info"
pub const GROUP_SET_GROUP_MEMBER_INFO: &str = "/group/set_group_member_info";
/// GetFullJoinedGroupIDs = "/group/get_full_join_group_ids"
pub const GROUP_GET_FULL_JOIN_GROUP_IDS: &str = "/group/get_full_join_group_ids";
/// GetFullGroupMemberUserIDs = "/group/get_full_group_member_user_ids"
pub const GROUP_GET_FULL_GROUP_MEMBER_USER_IDS: &str = "/group/get_full_group_member_user_ids";
