// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../event/types.dart';
import '../model/group.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'group.freezed.dart';

@freezed
sealed class GroupEvent with _$GroupEvent {
  const GroupEvent._();

  const factory GroupEvent.joinedGroupAdded(GroupInfo field0) =
      GroupEvent_JoinedGroupAdded;
  const factory GroupEvent.joinedGroupDeleted(GroupInfo field0) =
      GroupEvent_JoinedGroupDeleted;
  const factory GroupEvent.groupInfoChanged(GroupInfo field0) =
      GroupEvent_GroupInfoChanged;
  const factory GroupEvent.memberAdded(String field0) = GroupEvent_MemberAdded;
  const factory GroupEvent.memberDeleted(String field0) =
      GroupEvent_MemberDeleted;
  const factory GroupEvent.groupReadReceipt(List<GroupReadReceipt> field0) =
      GroupEvent_GroupReadReceipt;
}
